// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: market.proto

package marketservice

import (
	"context"

	"exchange-system/common/pb/market"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Depth         = market.Depth
	DepthItem     = market.DepthItem
	Kline         = market.Kline
	MarketData    = market.MarketData
	StreamRequest = market.StreamRequest
	Trade         = market.Trade

	MarketService interface {
		// 订阅市场数据流
		StreamMarketData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (market.MarketService_StreamMarketDataClient, error)
	}

	defaultMarketService struct {
		cli zrpc.Client
	}
)

func NewMarketService(cli zrpc.Client) MarketService {
	return &defaultMarketService{
		cli: cli,
	}
}

// 订阅市场数据流
func (m *defaultMarketService) StreamMarketData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (market.MarketService_StreamMarketDataClient, error) {
	client := market.NewMarketServiceClient(m.cli.Conn())
	return client.StreamMarketData(ctx, in, opts...)
}
