// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: account.proto

package accountClient

import (
	"context"

	"exchange-system/rpc/account/account"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FreezeRequest      = account.FreezeRequest
	FreezeResponse     = account.FreezeResponse
	GetBalanceRequest  = account.GetBalanceRequest
	GetBalanceResponse = account.GetBalanceResponse
	SettleRequest      = account.SettleRequest
	SettleResponse     = account.SettleResponse

	Account interface {
		GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
		Freeze(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*FreezeResponse, error)
		Unfreeze(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*FreezeResponse, error)
		Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleResponse, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.GetBalance(ctx, in, opts...)
}

func (m *defaultAccount) Freeze(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*FreezeResponse, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.Freeze(ctx, in, opts...)
}

func (m *defaultAccount) Unfreeze(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*FreezeResponse, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.Unfreeze(ctx, in, opts...)
}

func (m *defaultAccount) Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleResponse, error) {
	client := account.NewAccountClient(m.cli.Conn())
	return client.Settle(ctx, in, opts...)
}
