// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: common/proto/market.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// K线数据类型
type Kline struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Symbol         string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval       string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	OpenTime       int64                  `protobuf:"varint,3,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	Open           float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High           float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low            float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close          float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
	Volume         float64                `protobuf:"fixed64,8,opt,name=volume,proto3" json:"volume,omitempty"`
	CloseTime      int64                  `protobuf:"varint,9,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	IsClosed       bool                   `protobuf:"varint,10,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	EventTime      int64                  `protobuf:"varint,11,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`                   // 事件时间(ms)
	FirstTradeId   int64                  `protobuf:"varint,12,opt,name=first_trade_id,json=firstTradeId,proto3" json:"first_trade_id,omitempty"`        // 第一笔成交ID
	LastTradeId    int64                  `protobuf:"varint,13,opt,name=last_trade_id,json=lastTradeId,proto3" json:"last_trade_id,omitempty"`           // 末一笔成交ID
	NumTrades      int32                  `protobuf:"varint,14,opt,name=num_trades,json=numTrades,proto3" json:"num_trades,omitempty"`                   // 成交笔数
	QuoteVolume    float64                `protobuf:"fixed64,15,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`            // 成交额
	TakerBuyVolume float64                `protobuf:"fixed64,16,opt,name=taker_buy_volume,json=takerBuyVolume,proto3" json:"taker_buy_volume,omitempty"` // 主动买入成交量
	TakerBuyQuote  float64                `protobuf:"fixed64,17,opt,name=taker_buy_quote,json=takerBuyQuote,proto3" json:"taker_buy_quote,omitempty"`    // 主动买入成交额
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Kline) Reset() {
	*x = Kline{}
	mi := &file_common_proto_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kline) ProtoMessage() {}

func (x *Kline) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kline.ProtoReflect.Descriptor instead.
func (*Kline) Descriptor() ([]byte, []int) {
	return file_common_proto_market_proto_rawDescGZIP(), []int{0}
}

func (x *Kline) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Kline) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *Kline) GetOpenTime() int64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

func (x *Kline) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Kline) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Kline) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Kline) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Kline) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Kline) GetCloseTime() int64 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

func (x *Kline) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

func (x *Kline) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *Kline) GetFirstTradeId() int64 {
	if x != nil {
		return x.FirstTradeId
	}
	return 0
}

func (x *Kline) GetLastTradeId() int64 {
	if x != nil {
		return x.LastTradeId
	}
	return 0
}

func (x *Kline) GetNumTrades() int32 {
	if x != nil {
		return x.NumTrades
	}
	return 0
}

func (x *Kline) GetQuoteVolume() float64 {
	if x != nil {
		return x.QuoteVolume
	}
	return 0
}

func (x *Kline) GetTakerBuyVolume() float64 {
	if x != nil {
		return x.TakerBuyVolume
	}
	return 0
}

func (x *Kline) GetTakerBuyQuote() float64 {
	if x != nil {
		return x.TakerBuyQuote
	}
	return 0
}

// 深度数据
type Depth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Bids          []*DepthItem           `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*DepthItem           `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Depth) Reset() {
	*x = Depth{}
	mi := &file_common_proto_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Depth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Depth) ProtoMessage() {}

func (x *Depth) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Depth.ProtoReflect.Descriptor instead.
func (*Depth) Descriptor() ([]byte, []int) {
	return file_common_proto_market_proto_rawDescGZIP(), []int{1}
}

func (x *Depth) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Depth) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Depth) GetBids() []*DepthItem {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Depth) GetAsks() []*DepthItem {
	if x != nil {
		return x.Asks
	}
	return nil
}

type DepthItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthItem) Reset() {
	*x = DepthItem{}
	mi := &file_common_proto_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthItem) ProtoMessage() {}

func (x *DepthItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthItem.ProtoReflect.Descriptor instead.
func (*DepthItem) Descriptor() ([]byte, []int) {
	return file_common_proto_market_proto_rawDescGZIP(), []int{2}
}

func (x *DepthItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DepthItem) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// 交易数据
type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TradeId       int64                  `protobuf:"varint,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsBuyerMaker  bool                   `protobuf:"varint,6,opt,name=is_buyer_maker,json=isBuyerMaker,proto3" json:"is_buyer_maker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_common_proto_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_common_proto_market_proto_rawDescGZIP(), []int{3}
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetTradeId() int64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Trade) GetIsBuyerMaker() bool {
	if x != nil {
		return x.IsBuyerMaker
	}
	return false
}

// 市场数据流消息
type MarketData struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Type   string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "kline", "depth", "trade"
	Symbol string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*MarketData_Kline
	//	*MarketData_Depth
	//	*MarketData_Trade
	Data          isMarketData_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketData) Reset() {
	*x = MarketData{}
	mi := &file_common_proto_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketData) ProtoMessage() {}

func (x *MarketData) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketData.ProtoReflect.Descriptor instead.
func (*MarketData) Descriptor() ([]byte, []int) {
	return file_common_proto_market_proto_rawDescGZIP(), []int{4}
}

func (x *MarketData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MarketData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketData) GetData() isMarketData_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MarketData) GetKline() *Kline {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Kline); ok {
			return x.Kline
		}
	}
	return nil
}

func (x *MarketData) GetDepth() *Depth {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Depth); ok {
			return x.Depth
		}
	}
	return nil
}

func (x *MarketData) GetTrade() *Trade {
	if x != nil {
		if x, ok := x.Data.(*MarketData_Trade); ok {
			return x.Trade
		}
	}
	return nil
}

type isMarketData_Data interface {
	isMarketData_Data()
}

type MarketData_Kline struct {
	Kline *Kline `protobuf:"bytes,3,opt,name=kline,proto3,oneof"`
}

type MarketData_Depth struct {
	Depth *Depth `protobuf:"bytes,4,opt,name=depth,proto3,oneof"`
}

type MarketData_Trade struct {
	Trade *Trade `protobuf:"bytes,5,opt,name=trade,proto3,oneof"`
}

func (*MarketData_Kline) isMarketData_Data() {}

func (*MarketData_Depth) isMarketData_Data() {}

func (*MarketData_Trade) isMarketData_Data() {}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Types         []string               `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"` // kline, depth, trade
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_common_proto_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_market_proto_rawDescGZIP(), []int{5}
}

func (x *StreamRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *StreamRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_common_proto_market_proto protoreflect.FileDescriptor

const file_common_proto_market_proto_rawDesc = "" +
	"\n" +
	"\x19common/proto/market.proto\x12\x06market\"\xf9\x03\n" +
	"\x05Kline\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12\x1b\n" +
	"\topen_time\x18\x03 \x01(\x03R\bopenTime\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\b \x01(\x01R\x06volume\x12\x1d\n" +
	"\n" +
	"close_time\x18\t \x01(\x03R\tcloseTime\x12\x1b\n" +
	"\tis_closed\x18\n" +
	" \x01(\bR\bisClosed\x12\x1d\n" +
	"\n" +
	"event_time\x18\v \x01(\x03R\teventTime\x12$\n" +
	"\x0efirst_trade_id\x18\f \x01(\x03R\ffirstTradeId\x12\"\n" +
	"\rlast_trade_id\x18\r \x01(\x03R\vlastTradeId\x12\x1d\n" +
	"\n" +
	"num_trades\x18\x0e \x01(\x05R\tnumTrades\x12!\n" +
	"\fquote_volume\x18\x0f \x01(\x01R\vquoteVolume\x12(\n" +
	"\x10taker_buy_volume\x18\x10 \x01(\x01R\x0etakerBuyVolume\x12&\n" +
	"\x0ftaker_buy_quote\x18\x11 \x01(\x01R\rtakerBuyQuote\"\x8b\x01\n" +
	"\x05Depth\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12%\n" +
	"\x04bids\x18\x03 \x03(\v2\x11.market.DepthItemR\x04bids\x12%\n" +
	"\x04asks\x18\x04 \x03(\v2\x11.market.DepthItemR\x04asks\"=\n" +
	"\tDepthItem\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\"\xb0\x01\n" +
	"\x05Trade\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\x03R\atradeId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12$\n" +
	"\x0eis_buyer_maker\x18\x06 \x01(\bR\fisBuyerMaker\"\xb5\x01\n" +
	"\n" +
	"MarketData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12%\n" +
	"\x05kline\x18\x03 \x01(\v2\r.market.KlineH\x00R\x05kline\x12%\n" +
	"\x05depth\x18\x04 \x01(\v2\r.market.DepthH\x00R\x05depth\x12%\n" +
	"\x05trade\x18\x05 \x01(\v2\r.market.TradeH\x00R\x05tradeB\x06\n" +
	"\x04data\"?\n" +
	"\rStreamRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x14\n" +
	"\x05types\x18\x02 \x03(\tR\x05types2R\n" +
	"\rMarketService\x12A\n" +
	"\x10StreamMarketData\x12\x15.market.StreamRequest\x1a\x12.market.MarketData\"\x000\x01B\"Z exchange-system/common/pb/marketb\x06proto3"

var (
	file_common_proto_market_proto_rawDescOnce sync.Once
	file_common_proto_market_proto_rawDescData []byte
)

func file_common_proto_market_proto_rawDescGZIP() []byte {
	file_common_proto_market_proto_rawDescOnce.Do(func() {
		file_common_proto_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_market_proto_rawDesc), len(file_common_proto_market_proto_rawDesc)))
	})
	return file_common_proto_market_proto_rawDescData
}

var file_common_proto_market_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_market_proto_goTypes = []any{
	(*Kline)(nil),         // 0: market.Kline
	(*Depth)(nil),         // 1: market.Depth
	(*DepthItem)(nil),     // 2: market.DepthItem
	(*Trade)(nil),         // 3: market.Trade
	(*MarketData)(nil),    // 4: market.MarketData
	(*StreamRequest)(nil), // 5: market.StreamRequest
}
var file_common_proto_market_proto_depIdxs = []int32{
	2, // 0: market.Depth.bids:type_name -> market.DepthItem
	2, // 1: market.Depth.asks:type_name -> market.DepthItem
	0, // 2: market.MarketData.kline:type_name -> market.Kline
	1, // 3: market.MarketData.depth:type_name -> market.Depth
	3, // 4: market.MarketData.trade:type_name -> market.Trade
	5, // 5: market.MarketService.StreamMarketData:input_type -> market.StreamRequest
	4, // 6: market.MarketService.StreamMarketData:output_type -> market.MarketData
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_proto_market_proto_init() }
func file_common_proto_market_proto_init() {
	if File_common_proto_market_proto != nil {
		return
	}
	file_common_proto_market_proto_msgTypes[4].OneofWrappers = []any{
		(*MarketData_Kline)(nil),
		(*MarketData_Depth)(nil),
		(*MarketData_Trade)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_market_proto_rawDesc), len(file_common_proto_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_market_proto_goTypes,
		DependencyIndexes: file_common_proto_market_proto_depIdxs,
		MessageInfos:      file_common_proto_market_proto_msgTypes,
	}.Build()
	File_common_proto_market_proto = out.File
	file_common_proto_market_proto_goTypes = nil
	file_common_proto_market_proto_depIdxs = nil
}
