// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code int    `json:"code"` // 状态码
	Msg  string `json:"msg"`  // 消息
	Data string `json:"data"` // 数据
}

type GetBalanceReq struct {
	Currency string `form:"currency"`
}

type GetBalanceResp struct {
	Available string `json:"available"`
	Locked    string `json:"locked"`
	Total     string `json:"total"`
}

type GetOrderBookReq struct {
	Symbol string `form:"symbol"`
	Depth  int    `form:"depth,optional,default=20"`
}

type GetOrderBookResp struct {
	Bids      []OrderLevel `json:"bids"`
	Asks      []OrderLevel `json:"asks"`
	Timestamp int64        `json:\"timestamp\"`
}

type GetOrderReq struct {
	OrderID string `form:"order_id"`
}

type GetOrderResp struct {
	OrderID      string `json:"order_id"`
	UserID       string `json:"user_id"`
	Symbol       string `json:"symbol"`
	Side         string `json:"side"`
	Type         string `json:"type"`
	Price        string `json:"price"`
	Amount       string `json:"amount"`
	FilledAmount string `json:"filled_amount"`
	Status       string `json:"status"`
	CreateTime   int64  `json:"create_time"`
	UpdateTime   int64  `json:"update_time"`
}

type OrderLevel struct {
	Price  string `json:"price"`
	Amount string `json:"amount"`
}

type PlaceOrderReq struct {
	UserID        string `json:"user_id"`                  // 用户ID
	Symbol        string `json:"symbol"`                   // 交易对
	Side          string `json:"side"`                     // 买卖方向: buy/sell
	Type          string `json:"type"`                     // 订单类型: limit/market
	Price         string `json:"price"`                    // 价格
	Amount        string `json:"amount"`                   // 数量
	ClientOrderID string `json:"client_order_id,optional"` // 客户端订单ID
}

type PlaceOrderResp struct {
	OrderID  string `json:"order_id"`
	Status   string `json:"status"`
	ErrorMsg string `json:"error_msg,optional"`
}
