// rpc/account/account.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: rpc/account/account.proto

package account

import (
	types "exchange/common/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_rpc_account_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *types.Balance         `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_rpc_account_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetBalance() *types.Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type FreezeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeRequest) Reset() {
	*x = FreezeRequest{}
	mi := &file_rpc_account_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeRequest) ProtoMessage() {}

func (x *FreezeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeRequest.ProtoReflect.Descriptor instead.
func (*FreezeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_account_proto_rawDescGZIP(), []int{2}
}

func (x *FreezeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FreezeRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *FreezeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FreezeRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type FreezeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeResponse) Reset() {
	*x = FreezeResponse{}
	mi := &file_rpc_account_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeResponse) ProtoMessage() {}

func (x *FreezeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeResponse.ProtoReflect.Descriptor instead.
func (*FreezeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_account_proto_rawDescGZIP(), []int{3}
}

func (x *FreezeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FreezeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	BuyerId       string                 `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId      string                 `protobuf:"bytes,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,4,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency string                 `protobuf:"bytes,5,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Amount        string                 `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_rpc_account_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_rpc_account_account_proto_rawDescGZIP(), []int{4}
}

func (x *SettleRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *SettleRequest) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *SettleRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *SettleRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *SettleRequest) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

func (x *SettleRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SettleRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type SettleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleResponse) Reset() {
	*x = SettleResponse{}
	mi := &file_rpc_account_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleResponse) ProtoMessage() {}

func (x *SettleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_account_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleResponse.ProtoReflect.Descriptor instead.
func (*SettleResponse) Descriptor() ([]byte, []int) {
	return file_rpc_account_account_proto_rawDescGZIP(), []int{5}
}

func (x *SettleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SettleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_rpc_account_account_proto protoreflect.FileDescriptor

const file_rpc_account_account_proto_rawDesc = "" +
	"\n" +
	"\x19rpc/account/account.proto\x12\aaccount\x1a\x1bcommon/types/exchange.proto\"H\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"A\n" +
	"\x12GetBalanceResponse\x12+\n" +
	"\abalance\x18\x01 \x01(\v2\x11.exchange.BalanceR\abalance\"w\n" +
	"\rFreezeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"@\n" +
	"\x0eFreezeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xdc\x01\n" +
	"\rSettleRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x19\n" +
	"\bbuyer_id\x18\x02 \x01(\tR\abuyerId\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\tR\bsellerId\x12#\n" +
	"\rbase_currency\x18\x04 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0equote_currency\x18\x05 \x01(\tR\rquoteCurrency\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\a \x01(\tR\x06amount\"@\n" +
	"\x0eSettleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x83\x02\n" +
	"\aAccount\x12E\n" +
	"\n" +
	"GetBalance\x12\x1a.account.GetBalanceRequest\x1a\x1b.account.GetBalanceResponse\x129\n" +
	"\x06Freeze\x12\x16.account.FreezeRequest\x1a\x17.account.FreezeResponse\x12;\n" +
	"\bUnfreeze\x12\x16.account.FreezeRequest\x1a\x17.account.FreezeResponse\x129\n" +
	"\x06Settle\x12\x16.account.SettleRequest\x1a\x17.account.SettleResponseB\vZ\t./accountb\x06proto3"

var (
	file_rpc_account_account_proto_rawDescOnce sync.Once
	file_rpc_account_account_proto_rawDescData []byte
)

func file_rpc_account_account_proto_rawDescGZIP() []byte {
	file_rpc_account_account_proto_rawDescOnce.Do(func() {
		file_rpc_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_account_account_proto_rawDesc), len(file_rpc_account_account_proto_rawDesc)))
	})
	return file_rpc_account_account_proto_rawDescData
}

var file_rpc_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_account_account_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),  // 0: account.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 1: account.GetBalanceResponse
	(*FreezeRequest)(nil),      // 2: account.FreezeRequest
	(*FreezeResponse)(nil),     // 3: account.FreezeResponse
	(*SettleRequest)(nil),      // 4: account.SettleRequest
	(*SettleResponse)(nil),     // 5: account.SettleResponse
	(*types.Balance)(nil),      // 6: exchange.Balance
}
var file_rpc_account_account_proto_depIdxs = []int32{
	6, // 0: account.GetBalanceResponse.balance:type_name -> exchange.Balance
	0, // 1: account.Account.GetBalance:input_type -> account.GetBalanceRequest
	2, // 2: account.Account.Freeze:input_type -> account.FreezeRequest
	2, // 3: account.Account.Unfreeze:input_type -> account.FreezeRequest
	4, // 4: account.Account.Settle:input_type -> account.SettleRequest
	1, // 5: account.Account.GetBalance:output_type -> account.GetBalanceResponse
	3, // 6: account.Account.Freeze:output_type -> account.FreezeResponse
	3, // 7: account.Account.Unfreeze:output_type -> account.FreezeResponse
	5, // 8: account.Account.Settle:output_type -> account.SettleResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_account_account_proto_init() }
func file_rpc_account_account_proto_init() {
	if File_rpc_account_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_account_account_proto_rawDesc), len(file_rpc_account_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_account_account_proto_goTypes,
		DependencyIndexes: file_rpc_account_account_proto_depIdxs,
		MessageInfos:      file_rpc_account_account_proto_msgTypes,
	}.Build()
	File_rpc_account_account_proto = out.File
	file_rpc_account_account_proto_goTypes = nil
	file_rpc_account_account_proto_depIdxs = nil
}
