// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: execution.proto

package execution

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单请求
type OrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`                                     // BUY, SELL
	PositionSide  string                 `protobuf:"bytes,4,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"` // LONG, SHORT, BOTH
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"` // LIMIT, MARKET, STOP
	StopPrice     float64                `protobuf:"fixed64,8,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	ReduceOnly    bool                   `protobuf:"varint,9,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	ClosePosition bool                   `protobuf:"varint,10,opt,name=close_position,json=closePosition,proto3" json:"close_position,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,11,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"` // 客户端自定义订单ID（用于幂等防重）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRequest) Reset() {
	*x = OrderRequest{}
	mi := &file_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRequest) ProtoMessage() {}

func (x *OrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRequest.ProtoReflect.Descriptor instead.
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *OrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderRequest) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OrderRequest) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

func (x *OrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderRequest) GetStopPrice() float64 {
	if x != nil {
		return x.StopPrice
	}
	return 0
}

func (x *OrderRequest) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *OrderRequest) GetClosePosition() bool {
	if x != nil {
		return x.ClosePosition
	}
	return false
}

func (x *OrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

// 订单状态
type OrderStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId    string                 `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Symbol           string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // NEW, PARTIALLY_FILLED, FILLED, CANCELED, REJECTED
	Side             string                 `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	ExecutedQuantity float64                `protobuf:"fixed64,6,opt,name=executed_quantity,json=executedQuantity,proto3" json:"executed_quantity,omitempty"`
	AvgPrice         float64                `protobuf:"fixed64,7,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Commission       float64                `protobuf:"fixed64,8,opt,name=commission,proto3" json:"commission,omitempty"`
	CommissionAsset  string                 `protobuf:"bytes,9,opt,name=commission_asset,json=commissionAsset,proto3" json:"commission_asset,omitempty"`
	TransactTime     int64                  `protobuf:"varint,10,opt,name=transact_time,json=transactTime,proto3" json:"transact_time,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	PositionSide     string                 `protobuf:"bytes,12,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"` // 持仓方向
	Slippage         float64                `protobuf:"fixed64,13,opt,name=slippage,proto3" json:"slippage,omitempty"`                           // 滑点金额
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

func (x *OrderStatus) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatus) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *OrderStatus) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderStatus) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OrderStatus) GetExecutedQuantity() float64 {
	if x != nil {
		return x.ExecutedQuantity
	}
	return 0
}

func (x *OrderStatus) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *OrderStatus) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *OrderStatus) GetCommissionAsset() string {
	if x != nil {
		return x.CommissionAsset
	}
	return ""
}

func (x *OrderStatus) GetTransactTime() int64 {
	if x != nil {
		return x.TransactTime
	}
	return 0
}

func (x *OrderStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *OrderStatus) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

func (x *OrderStatus) GetSlippage() float64 {
	if x != nil {
		return x.Slippage
	}
	return 0
}

// 账户信息
type AccountInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalWalletBalance float64                `protobuf:"fixed64,1,opt,name=total_wallet_balance,json=totalWalletBalance,proto3" json:"total_wallet_balance,omitempty"`
	TotalUnrealizedPnl float64                `protobuf:"fixed64,2,opt,name=total_unrealized_pnl,json=totalUnrealizedPnl,proto3" json:"total_unrealized_pnl,omitempty"`
	TotalMarginBalance float64                `protobuf:"fixed64,3,opt,name=total_margin_balance,json=totalMarginBalance,proto3" json:"total_margin_balance,omitempty"`
	AvailableBalance   float64                `protobuf:"fixed64,4,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	MaxWithdrawAmount  float64                `protobuf:"fixed64,5,opt,name=max_withdraw_amount,json=maxWithdrawAmount,proto3" json:"max_withdraw_amount,omitempty"`
	Positions          []*Position            `protobuf:"bytes,6,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{2}
}

func (x *AccountInfo) GetTotalWalletBalance() float64 {
	if x != nil {
		return x.TotalWalletBalance
	}
	return 0
}

func (x *AccountInfo) GetTotalUnrealizedPnl() float64 {
	if x != nil {
		return x.TotalUnrealizedPnl
	}
	return 0
}

func (x *AccountInfo) GetTotalMarginBalance() float64 {
	if x != nil {
		return x.TotalMarginBalance
	}
	return 0
}

func (x *AccountInfo) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountInfo) GetMaxWithdrawAmount() float64 {
	if x != nil {
		return x.MaxWithdrawAmount
	}
	return 0
}

func (x *AccountInfo) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type Position struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Symbol                 string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PositionAmount         float64                `protobuf:"fixed64,2,opt,name=position_amount,json=positionAmount,proto3" json:"position_amount,omitempty"`
	EntryPrice             float64                `protobuf:"fixed64,3,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	MarkPrice              float64                `protobuf:"fixed64,4,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	UnrealizedPnl          float64                `protobuf:"fixed64,5,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	LiquidationPrice       float64                `protobuf:"fixed64,6,opt,name=liquidation_price,json=liquidationPrice,proto3" json:"liquidation_price,omitempty"`
	Leverage               float64                `protobuf:"fixed64,7,opt,name=leverage,proto3" json:"leverage,omitempty"`
	MarginType             string                 `protobuf:"bytes,8,opt,name=margin_type,json=marginType,proto3" json:"margin_type,omitempty"`
	PositionSide           string                 `protobuf:"bytes,9,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"`
	BreakEvenPrice         float64                `protobuf:"fixed64,10,opt,name=break_even_price,json=breakEvenPrice,proto3" json:"break_even_price,omitempty"`
	Notional               float64                `protobuf:"fixed64,11,opt,name=notional,proto3" json:"notional,omitempty"`
	InitialMargin          float64                `protobuf:"fixed64,12,opt,name=initial_margin,json=initialMargin,proto3" json:"initial_margin,omitempty"`
	MaintMargin            float64                `protobuf:"fixed64,13,opt,name=maint_margin,json=maintMargin,proto3" json:"maint_margin,omitempty"`
	PositionInitialMargin  float64                `protobuf:"fixed64,14,opt,name=position_initial_margin,json=positionInitialMargin,proto3" json:"position_initial_margin,omitempty"`
	OpenOrderInitialMargin float64                `protobuf:"fixed64,15,opt,name=open_order_initial_margin,json=openOrderInitialMargin,proto3" json:"open_order_initial_margin,omitempty"`
	IsolatedMargin         float64                `protobuf:"fixed64,16,opt,name=isolated_margin,json=isolatedMargin,proto3" json:"isolated_margin,omitempty"`
	BidNotional            float64                `protobuf:"fixed64,17,opt,name=bid_notional,json=bidNotional,proto3" json:"bid_notional,omitempty"`
	AskNotional            float64                `protobuf:"fixed64,18,opt,name=ask_notional,json=askNotional,proto3" json:"ask_notional,omitempty"`
	UpdateTime             int64                  `protobuf:"varint,19,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Adl                    int32                  `protobuf:"varint,20,opt,name=adl,proto3" json:"adl,omitempty"`
	PnlPercent             float64                `protobuf:"fixed64,21,opt,name=pnl_percent,json=pnlPercent,proto3" json:"pnl_percent,omitempty"`
	StopLossPrice          float64                `protobuf:"fixed64,22,opt,name=stop_loss_price,json=stopLossPrice,proto3" json:"stop_loss_price,omitempty"`
	TakeProfitPrice        float64                `protobuf:"fixed64,23,opt,name=take_profit_price,json=takeProfitPrice,proto3" json:"take_profit_price,omitempty"`
	FundingRate            float64                `protobuf:"fixed64,24,opt,name=funding_rate,json=fundingRate,proto3" json:"funding_rate,omitempty"`
	EstimatedFundingFee    float64                `protobuf:"fixed64,25,opt,name=estimated_funding_fee,json=estimatedFundingFee,proto3" json:"estimated_funding_fee,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{3}
}

func (x *Position) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Position) GetPositionAmount() float64 {
	if x != nil {
		return x.PositionAmount
	}
	return 0
}

func (x *Position) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *Position) GetMarkPrice() float64 {
	if x != nil {
		return x.MarkPrice
	}
	return 0
}

func (x *Position) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *Position) GetLiquidationPrice() float64 {
	if x != nil {
		return x.LiquidationPrice
	}
	return 0
}

func (x *Position) GetLeverage() float64 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *Position) GetMarginType() string {
	if x != nil {
		return x.MarginType
	}
	return ""
}

func (x *Position) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

func (x *Position) GetBreakEvenPrice() float64 {
	if x != nil {
		return x.BreakEvenPrice
	}
	return 0
}

func (x *Position) GetNotional() float64 {
	if x != nil {
		return x.Notional
	}
	return 0
}

func (x *Position) GetInitialMargin() float64 {
	if x != nil {
		return x.InitialMargin
	}
	return 0
}

func (x *Position) GetMaintMargin() float64 {
	if x != nil {
		return x.MaintMargin
	}
	return 0
}

func (x *Position) GetPositionInitialMargin() float64 {
	if x != nil {
		return x.PositionInitialMargin
	}
	return 0
}

func (x *Position) GetOpenOrderInitialMargin() float64 {
	if x != nil {
		return x.OpenOrderInitialMargin
	}
	return 0
}

func (x *Position) GetIsolatedMargin() float64 {
	if x != nil {
		return x.IsolatedMargin
	}
	return 0
}

func (x *Position) GetBidNotional() float64 {
	if x != nil {
		return x.BidNotional
	}
	return 0
}

func (x *Position) GetAskNotional() float64 {
	if x != nil {
		return x.AskNotional
	}
	return 0
}

func (x *Position) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Position) GetAdl() int32 {
	if x != nil {
		return x.Adl
	}
	return 0
}

func (x *Position) GetPnlPercent() float64 {
	if x != nil {
		return x.PnlPercent
	}
	return 0
}

func (x *Position) GetStopLossPrice() float64 {
	if x != nil {
		return x.StopLossPrice
	}
	return 0
}

func (x *Position) GetTakeProfitPrice() float64 {
	if x != nil {
		return x.TakeProfitPrice
	}
	return 0
}

func (x *Position) GetFundingRate() float64 {
	if x != nil {
		return x.FundingRate
	}
	return 0
}

func (x *Position) GetEstimatedFundingFee() float64 {
	if x != nil {
		return x.EstimatedFundingFee
	}
	return 0
}

type OrderCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,3,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelRequest) Reset() {
	*x = OrderCancelRequest{}
	mi := &file_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelRequest) ProtoMessage() {}

func (x *OrderCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelRequest.ProtoReflect.Descriptor instead.
func (*OrderCancelRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{4}
}

func (x *OrderCancelRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderCancelRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCancelRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

type OrderQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,3,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQuery) Reset() {
	*x = OrderQuery{}
	mi := &file_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQuery) ProtoMessage() {}

func (x *OrderQuery) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQuery.ProtoReflect.Descriptor instead.
func (*OrderQuery) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{5}
}

func (x *OrderQuery) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderQuery) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderQuery) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

type AccountQuery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncludePositions bool                   `protobuf:"varint,1,opt,name=include_positions,json=includePositions,proto3" json:"include_positions,omitempty"`
	Symbol           string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountQuery) Reset() {
	*x = AccountQuery{}
	mi := &file_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountQuery) ProtoMessage() {}

func (x *AccountQuery) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountQuery.ProtoReflect.Descriptor instead.
func (*AccountQuery) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{6}
}

func (x *AccountQuery) GetIncludePositions() bool {
	if x != nil {
		return x.IncludePositions
	}
	return false
}

func (x *AccountQuery) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_execution_proto protoreflect.FileDescriptor

const file_execution_proto_rawDesc = "" +
	"\n" +
	"\x0fexecution.proto\x12\texecution\"\xd5\x02\n" +
	"\fOrderRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12#\n" +
	"\rposition_side\x18\x04 \x01(\tR\fpositionSide\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"stop_price\x18\b \x01(\x01R\tstopPrice\x12\x1f\n" +
	"\vreduce_only\x18\t \x01(\bR\n" +
	"reduceOnly\x12%\n" +
	"\x0eclose_position\x18\n" +
	" \x01(\bR\rclosePosition\x12&\n" +
	"\x0fclient_order_id\x18\v \x01(\tR\rclientOrderId\"\xb4\x03\n" +
	"\vOrderStatus\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x02 \x01(\tR\rclientOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04side\x18\x05 \x01(\tR\x04side\x12+\n" +
	"\x11executed_quantity\x18\x06 \x01(\x01R\x10executedQuantity\x12\x1b\n" +
	"\tavg_price\x18\a \x01(\x01R\bavgPrice\x12\x1e\n" +
	"\n" +
	"commission\x18\b \x01(\x01R\n" +
	"commission\x12)\n" +
	"\x10commission_asset\x18\t \x01(\tR\x0fcommissionAsset\x12#\n" +
	"\rtransact_time\x18\n" +
	" \x01(\x03R\ftransactTime\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12#\n" +
	"\rposition_side\x18\f \x01(\tR\fpositionSide\x12\x1a\n" +
	"\bslippage\x18\r \x01(\x01R\bslippage\"\xb3\x02\n" +
	"\vAccountInfo\x120\n" +
	"\x14total_wallet_balance\x18\x01 \x01(\x01R\x12totalWalletBalance\x120\n" +
	"\x14total_unrealized_pnl\x18\x02 \x01(\x01R\x12totalUnrealizedPnl\x120\n" +
	"\x14total_margin_balance\x18\x03 \x01(\x01R\x12totalMarginBalance\x12+\n" +
	"\x11available_balance\x18\x04 \x01(\x01R\x10availableBalance\x12.\n" +
	"\x13max_withdraw_amount\x18\x05 \x01(\x01R\x11maxWithdrawAmount\x121\n" +
	"\tpositions\x18\x06 \x03(\v2\x13.execution.PositionR\tpositions\"\xb2\a\n" +
	"\bPosition\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12'\n" +
	"\x0fposition_amount\x18\x02 \x01(\x01R\x0epositionAmount\x12\x1f\n" +
	"\ventry_price\x18\x03 \x01(\x01R\n" +
	"entryPrice\x12\x1d\n" +
	"\n" +
	"mark_price\x18\x04 \x01(\x01R\tmarkPrice\x12%\n" +
	"\x0eunrealized_pnl\x18\x05 \x01(\x01R\runrealizedPnl\x12+\n" +
	"\x11liquidation_price\x18\x06 \x01(\x01R\x10liquidationPrice\x12\x1a\n" +
	"\bleverage\x18\a \x01(\x01R\bleverage\x12\x1f\n" +
	"\vmargin_type\x18\b \x01(\tR\n" +
	"marginType\x12#\n" +
	"\rposition_side\x18\t \x01(\tR\fpositionSide\x12(\n" +
	"\x10break_even_price\x18\n" +
	" \x01(\x01R\x0ebreakEvenPrice\x12\x1a\n" +
	"\bnotional\x18\v \x01(\x01R\bnotional\x12%\n" +
	"\x0einitial_margin\x18\f \x01(\x01R\rinitialMargin\x12!\n" +
	"\fmaint_margin\x18\r \x01(\x01R\vmaintMargin\x126\n" +
	"\x17position_initial_margin\x18\x0e \x01(\x01R\x15positionInitialMargin\x129\n" +
	"\x19open_order_initial_margin\x18\x0f \x01(\x01R\x16openOrderInitialMargin\x12'\n" +
	"\x0fisolated_margin\x18\x10 \x01(\x01R\x0eisolatedMargin\x12!\n" +
	"\fbid_notional\x18\x11 \x01(\x01R\vbidNotional\x12!\n" +
	"\fask_notional\x18\x12 \x01(\x01R\vaskNotional\x12\x1f\n" +
	"\vupdate_time\x18\x13 \x01(\x03R\n" +
	"updateTime\x12\x10\n" +
	"\x03adl\x18\x14 \x01(\x05R\x03adl\x12\x1f\n" +
	"\vpnl_percent\x18\x15 \x01(\x01R\n" +
	"pnlPercent\x12&\n" +
	"\x0fstop_loss_price\x18\x16 \x01(\x01R\rstopLossPrice\x12*\n" +
	"\x11take_profit_price\x18\x17 \x01(\x01R\x0ftakeProfitPrice\x12!\n" +
	"\ffunding_rate\x18\x18 \x01(\x01R\vfundingRate\x122\n" +
	"\x15estimated_funding_fee\x18\x19 \x01(\x01R\x13estimatedFundingFee\"o\n" +
	"\x12OrderCancelRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x03 \x01(\tR\rclientOrderId\"g\n" +
	"\n" +
	"OrderQuery\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x03 \x01(\tR\rclientOrderId\"S\n" +
	"\fAccountQuery\x12+\n" +
	"\x11include_positions\x18\x01 \x01(\bR\x10includePositions\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol2\xa4\x02\n" +
	"\x10ExecutionService\x12@\n" +
	"\vCreateOrder\x12\x17.execution.OrderRequest\x1a\x16.execution.OrderStatus\"\x00\x12F\n" +
	"\vCancelOrder\x12\x1d.execution.OrderCancelRequest\x1a\x16.execution.OrderStatus\"\x00\x12A\n" +
	"\x0eGetOrderStatus\x12\x15.execution.OrderQuery\x1a\x16.execution.OrderStatus\"\x00\x12C\n" +
	"\x0eGetAccountInfo\x12\x17.execution.AccountQuery\x1a\x16.execution.AccountInfo\"\x00B\rZ\v./executionb\x06proto3"

var (
	file_execution_proto_rawDescOnce sync.Once
	file_execution_proto_rawDescData []byte
)

func file_execution_proto_rawDescGZIP() []byte {
	file_execution_proto_rawDescOnce.Do(func() {
		file_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)))
	})
	return file_execution_proto_rawDescData
}

var file_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_execution_proto_goTypes = []any{
	(*OrderRequest)(nil),       // 0: execution.OrderRequest
	(*OrderStatus)(nil),        // 1: execution.OrderStatus
	(*AccountInfo)(nil),        // 2: execution.AccountInfo
	(*Position)(nil),           // 3: execution.Position
	(*OrderCancelRequest)(nil), // 4: execution.OrderCancelRequest
	(*OrderQuery)(nil),         // 5: execution.OrderQuery
	(*AccountQuery)(nil),       // 6: execution.AccountQuery
}
var file_execution_proto_depIdxs = []int32{
	3, // 0: execution.AccountInfo.positions:type_name -> execution.Position
	0, // 1: execution.ExecutionService.CreateOrder:input_type -> execution.OrderRequest
	4, // 2: execution.ExecutionService.CancelOrder:input_type -> execution.OrderCancelRequest
	5, // 3: execution.ExecutionService.GetOrderStatus:input_type -> execution.OrderQuery
	6, // 4: execution.ExecutionService.GetAccountInfo:input_type -> execution.AccountQuery
	1, // 5: execution.ExecutionService.CreateOrder:output_type -> execution.OrderStatus
	1, // 6: execution.ExecutionService.CancelOrder:output_type -> execution.OrderStatus
	1, // 7: execution.ExecutionService.GetOrderStatus:output_type -> execution.OrderStatus
	2, // 8: execution.ExecutionService.GetAccountInfo:output_type -> execution.AccountInfo
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_execution_proto_init() }
func file_execution_proto_init() {
	if File_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_proto_goTypes,
		DependencyIndexes: file_execution_proto_depIdxs,
		MessageInfos:      file_execution_proto_msgTypes,
	}.Build()
	File_execution_proto = out.File
	file_execution_proto_goTypes = nil
	file_execution_proto_depIdxs = nil
}
