// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"exchange-system/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/balance/:currency",
				Handler: GetBalanceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/depth",
				Handler: GetOrderBookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/order",
				Handler: PlaceOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/order/:order_id",
				Handler: CancelOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/order/:order_id",
				Handler: GetOrderHandler(serverCtx),
			},
		},
	)
}
