// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: execution.proto

package executionservice

import (
	"context"

	"exchange-system/common/pb/execution"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccountInfo        = execution.AccountInfo
	AccountQuery       = execution.AccountQuery
	OrderCancelRequest = execution.OrderCancelRequest
	OrderQuery         = execution.OrderQuery
	OrderRequest       = execution.OrderRequest
	OrderStatus        = execution.OrderStatus
	Position           = execution.Position

	ExecutionService interface {
		// 创建订单
		CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderStatus, error)
		// 取消订单
		CancelOrder(ctx context.Context, in *OrderCancelRequest, opts ...grpc.CallOption) (*OrderStatus, error)
		// 获取订单状态
		GetOrderStatus(ctx context.Context, in *OrderQuery, opts ...grpc.CallOption) (*OrderStatus, error)
		// 获取账户信息
		GetAccountInfo(ctx context.Context, in *AccountQuery, opts ...grpc.CallOption) (*AccountInfo, error)
	}

	defaultExecutionService struct {
		cli zrpc.Client
	}
)

func NewExecutionService(cli zrpc.Client) ExecutionService {
	return &defaultExecutionService{
		cli: cli,
	}
}

// 创建订单
func (m *defaultExecutionService) CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderStatus, error) {
	client := execution.NewExecutionServiceClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

// 取消订单
func (m *defaultExecutionService) CancelOrder(ctx context.Context, in *OrderCancelRequest, opts ...grpc.CallOption) (*OrderStatus, error) {
	client := execution.NewExecutionServiceClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

// 获取订单状态
func (m *defaultExecutionService) GetOrderStatus(ctx context.Context, in *OrderQuery, opts ...grpc.CallOption) (*OrderStatus, error) {
	client := execution.NewExecutionServiceClient(m.cli.Conn())
	return client.GetOrderStatus(ctx, in, opts...)
}

// 获取账户信息
func (m *defaultExecutionService) GetAccountInfo(ctx context.Context, in *AccountQuery, opts ...grpc.CallOption) (*AccountInfo, error) {
	client := execution.NewExecutionServiceClient(m.cli.Conn())
	return client.GetAccountInfo(ctx, in, opts...)
}
