// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: execution.proto

package server

import (
	"context"

	"exchange-system/app/execution/rpc/internal/logic"
	"exchange-system/app/execution/rpc/internal/svc"
	"exchange-system/common/pb/execution"
)

type ExecutionServiceServer struct {
	svcCtx *svc.ServiceContext
	execution.UnimplementedExecutionServiceServer
}

func NewExecutionServiceServer(svcCtx *svc.ServiceContext) *ExecutionServiceServer {
	return &ExecutionServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建订单
func (s *ExecutionServiceServer) CreateOrder(ctx context.Context, in *execution.OrderRequest) (*execution.OrderStatus, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// 取消订单
func (s *ExecutionServiceServer) CancelOrder(ctx context.Context, in *execution.OrderCancelRequest) (*execution.OrderStatus, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

// 获取订单状态
func (s *ExecutionServiceServer) GetOrderStatus(ctx context.Context, in *execution.OrderQuery) (*execution.OrderStatus, error) {
	l := logic.NewGetOrderStatusLogic(ctx, s.svcCtx)
	return l.GetOrderStatus(in)
}

// 获取账户信息
func (s *ExecutionServiceServer) GetAccountInfo(ctx context.Context, in *execution.AccountQuery) (*execution.AccountInfo, error) {
	l := logic.NewGetAccountInfoLogic(ctx, s.svcCtx)
	return l.GetAccountInfo(in)
}
