// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: account.proto

package server

import (
	"context"

	"exchange-system/rpc/account/account"
	"exchange-system/rpc/account/internal/logic"
	"exchange-system/rpc/account/internal/svc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	account.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) GetBalance(ctx context.Context, in *account.GetBalanceRequest) (*account.GetBalanceResponse, error) {
	l := logic.NewGetBalanceLogic(ctx, s.svcCtx)
	return l.GetBalance(in)
}

func (s *AccountServer) Freeze(ctx context.Context, in *account.FreezeRequest) (*account.FreezeResponse, error) {
	l := logic.NewFreezeLogic(ctx, s.svcCtx)
	return l.Freeze(in)
}

func (s *AccountServer) Unfreeze(ctx context.Context, in *account.FreezeRequest) (*account.FreezeResponse, error) {
	l := logic.NewUnfreezeLogic(ctx, s.svcCtx)
	return l.Unfreeze(in)
}

func (s *AccountServer) Settle(ctx context.Context, in *account.SettleRequest) (*account.SettleResponse, error) {
	l := logic.NewSettleLogic(ctx, s.svcCtx)
	return l.Settle(in)
}
