// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: market.proto

package server

import (
	"exchange-system/app/market/rpc/internal/logic"
	"exchange-system/app/market/rpc/internal/svc"
	"exchange-system/common/pb/market"
)

type MarketServiceServer struct {
	svcCtx *svc.ServiceContext
	market.UnimplementedMarketServiceServer
}

func NewMarketServiceServer(svcCtx *svc.ServiceContext) *MarketServiceServer {
	return &MarketServiceServer{
		svcCtx: svcCtx,
	}
}

// 订阅市场数据流
func (s *MarketServiceServer) StreamMarketData(in *market.StreamRequest, stream market.MarketService_StreamMarketDataServer) error {
	l := logic.NewStreamMarketDataLogic(stream.Context(), s.svcCtx)
	return l.StreamMarketData(in, stream)
}
