// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: matching.proto

package matchingClient

import (
	"context"

	"exchange-system/rpc/matching/exchange/rpc/matching/matching"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderRequest   = matching.CancelOrderRequest
	CancelOrderResponse  = matching.CancelOrderResponse
	GetOrderBookRequest  = matching.GetOrderBookRequest
	GetOrderBookResponse = matching.GetOrderBookResponse
	OrderRequest         = matching.OrderRequest
	OrderResponse        = matching.OrderResponse

	Matching interface {
		SubmitOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
		CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
		GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error)
	}

	defaultMatching struct {
		cli zrpc.Client
	}
)

func NewMatching(cli zrpc.Client) Matching {
	return &defaultMatching{
		cli: cli,
	}
}

func (m *defaultMatching) SubmitOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	client := matching.NewMatchingClient(m.cli.Conn())
	return client.SubmitOrder(ctx, in, opts...)
}

func (m *defaultMatching) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	client := matching.NewMatchingClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

func (m *defaultMatching) GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error) {
	client := matching.NewMatchingClient(m.cli.Conn())
	return client.GetOrderBook(ctx, in, opts...)
}
