// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package orderservice

import (
	"context"

	"exchange-system/common/pb/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AllOrderItem        = order.AllOrderItem
	AllOrderResponse    = order.AllOrderResponse
	EmptyRequest        = order.EmptyRequest
	FundingFeeItem      = order.FundingFeeItem
	FundingFeeResponse  = order.FundingFeeResponse
	FundingRateItem     = order.FundingRateItem
	FundingRateResponse = order.FundingRateResponse
	IncomeItem          = order.IncomeItem
	IncomeResponse      = order.IncomeResponse
	OpenOrderItem       = order.OpenOrderItem
	OpenOrderResponse   = order.OpenOrderResponse
	OrderQueryRequest   = order.OrderQueryRequest
	UserTradeItem       = order.UserTradeItem
	UserTradeResponse   = order.UserTradeResponse

	OrderService interface {
		// 查询当前委托（未成交订单）
		GetOpenOrders(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*OpenOrderResponse, error)
		// 查询历史委托
		GetAllOrders(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*AllOrderResponse, error)
		// 查询历史成交
		GetUserTrades(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*UserTradeResponse, error)
		// 查询资金流水
		GetIncomeHistory(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*IncomeResponse, error)
		// 查询资金费率历史
		GetFundingRateHistory(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*FundingRateResponse, error)
		// 查询资金费用
		GetFundingFees(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*FundingFeeResponse, error)
		// 拉取全部数据并保存到本地 JSONL
		FetchAllData(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// 查询当前委托（未成交订单）
func (m *defaultOrderService) GetOpenOrders(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*OpenOrderResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.GetOpenOrders(ctx, in, opts...)
}

// 查询历史委托
func (m *defaultOrderService) GetAllOrders(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*AllOrderResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.GetAllOrders(ctx, in, opts...)
}

// 查询历史成交
func (m *defaultOrderService) GetUserTrades(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*UserTradeResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.GetUserTrades(ctx, in, opts...)
}

// 查询资金流水
func (m *defaultOrderService) GetIncomeHistory(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*IncomeResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.GetIncomeHistory(ctx, in, opts...)
}

// 查询资金费率历史
func (m *defaultOrderService) GetFundingRateHistory(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*FundingRateResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.GetFundingRateHistory(ctx, in, opts...)
}

// 查询资金费用
func (m *defaultOrderService) GetFundingFees(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*FundingFeeResponse, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.GetFundingFees(ctx, in, opts...)
}

// 拉取全部数据并保存到本地 JSONL
func (m *defaultOrderService) FetchAllData(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	client := order.NewOrderServiceClient(m.cli.Conn())
	return client.FetchAllData(ctx, in, opts...)
}
