// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用查询请求
type OrderQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                           // 交易对（如 ETHUSDT），部分接口必填
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`   // 起始时间（毫秒时间戳），0=不限制
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`         // 结束时间（毫秒时间戳），0=不限制
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                            // 返回数量限制，0=使用默认值
	IncomeType    string                 `protobuf:"bytes,5,opt,name=income_type,json=incomeType,proto3" json:"income_type,omitempty"` // 资金流水类型过滤（仅资金流水接口使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQueryRequest) Reset() {
	*x = OrderQueryRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQueryRequest) ProtoMessage() {}

func (x *OrderQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQueryRequest.ProtoReflect.Descriptor instead.
func (*OrderQueryRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderQueryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderQueryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *OrderQueryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *OrderQueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *OrderQueryRequest) GetIncomeType() string {
	if x != nil {
		return x.IncomeType
	}
	return ""
}

// 当前委托条目
type OpenOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	PositionSide  string                 `protobuf:"bytes,5,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	OrigQty       string                 `protobuf:"bytes,7,opt,name=orig_qty,json=origQty,proto3" json:"orig_qty,omitempty"`
	ExecutedQty   string                 `protobuf:"bytes,8,opt,name=executed_qty,json=executedQty,proto3" json:"executed_qty,omitempty"`
	AvgPrice      string                 `protobuf:"bytes,9,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Price         string                 `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty"`
	StopPrice     string                 `protobuf:"bytes,11,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,12,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Time          int64                  `protobuf:"varint,13,opt,name=time,proto3" json:"time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,14,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ReduceOnly    bool                   `protobuf:"varint,15,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	ClosePosition bool                   `protobuf:"varint,16,opt,name=close_position,json=closePosition,proto3" json:"close_position,omitempty"`
	TimeInForce   string                 `protobuf:"bytes,17,opt,name=time_in_force,json=timeInForce,proto3" json:"time_in_force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenOrderItem) Reset() {
	*x = OpenOrderItem{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrderItem) ProtoMessage() {}

func (x *OpenOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrderItem.ProtoReflect.Descriptor instead.
func (*OpenOrderItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *OpenOrderItem) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OpenOrderItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OpenOrderItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OpenOrderItem) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *OpenOrderItem) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

func (x *OpenOrderItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OpenOrderItem) GetOrigQty() string {
	if x != nil {
		return x.OrigQty
	}
	return ""
}

func (x *OpenOrderItem) GetExecutedQty() string {
	if x != nil {
		return x.ExecutedQty
	}
	return ""
}

func (x *OpenOrderItem) GetAvgPrice() string {
	if x != nil {
		return x.AvgPrice
	}
	return ""
}

func (x *OpenOrderItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OpenOrderItem) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *OpenOrderItem) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *OpenOrderItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *OpenOrderItem) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *OpenOrderItem) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *OpenOrderItem) GetClosePosition() bool {
	if x != nil {
		return x.ClosePosition
	}
	return false
}

func (x *OpenOrderItem) GetTimeInForce() string {
	if x != nil {
		return x.TimeInForce
	}
	return ""
}

// 历史委托条目
type PositionAllocatorStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Template       string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	RouteBucket    string                 `protobuf:"bytes,2,opt,name=route_bucket,json=routeBucket,proto3" json:"route_bucket,omitempty"`
	RouteReason    string                 `protobuf:"bytes,3,opt,name=route_reason,json=routeReason,proto3" json:"route_reason,omitempty"`
	Score          float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	ScoreSource    string                 `protobuf:"bytes,5,opt,name=score_source,json=scoreSource,proto3" json:"score_source,omitempty"`
	BucketBudget   float64                `protobuf:"fixed64,6,opt,name=bucket_budget,json=bucketBudget,proto3" json:"bucket_budget,omitempty"`
	StrategyWeight float64                `protobuf:"fixed64,7,opt,name=strategy_weight,json=strategyWeight,proto3" json:"strategy_weight,omitempty"`
	SymbolWeight   float64                `protobuf:"fixed64,8,opt,name=symbol_weight,json=symbolWeight,proto3" json:"symbol_weight,omitempty"`
	RiskScale      float64                `protobuf:"fixed64,9,opt,name=risk_scale,json=riskScale,proto3" json:"risk_scale,omitempty"`
	PositionBudget float64                `protobuf:"fixed64,10,opt,name=position_budget,json=positionBudget,proto3" json:"position_budget,omitempty"`
	TradingPaused  bool                   `protobuf:"varint,11,opt,name=trading_paused,json=tradingPaused,proto3" json:"trading_paused,omitempty"`
	PauseReason    string                 `protobuf:"bytes,12,opt,name=pause_reason,json=pauseReason,proto3" json:"pause_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PositionAllocatorStatus) Reset() {
	*x = PositionAllocatorStatus{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionAllocatorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionAllocatorStatus) ProtoMessage() {}

func (x *PositionAllocatorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionAllocatorStatus.ProtoReflect.Descriptor instead.
func (*PositionAllocatorStatus) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *PositionAllocatorStatus) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *PositionAllocatorStatus) GetRouteBucket() string {
	if x != nil {
		return x.RouteBucket
	}
	return ""
}

func (x *PositionAllocatorStatus) GetRouteReason() string {
	if x != nil {
		return x.RouteReason
	}
	return ""
}

func (x *PositionAllocatorStatus) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PositionAllocatorStatus) GetScoreSource() string {
	if x != nil {
		return x.ScoreSource
	}
	return ""
}

func (x *PositionAllocatorStatus) GetBucketBudget() float64 {
	if x != nil {
		return x.BucketBudget
	}
	return 0
}

func (x *PositionAllocatorStatus) GetStrategyWeight() float64 {
	if x != nil {
		return x.StrategyWeight
	}
	return 0
}

func (x *PositionAllocatorStatus) GetSymbolWeight() float64 {
	if x != nil {
		return x.SymbolWeight
	}
	return 0
}

func (x *PositionAllocatorStatus) GetRiskScale() float64 {
	if x != nil {
		return x.RiskScale
	}
	return 0
}

func (x *PositionAllocatorStatus) GetPositionBudget() float64 {
	if x != nil {
		return x.PositionBudget
	}
	return 0
}

func (x *PositionAllocatorStatus) GetTradingPaused() bool {
	if x != nil {
		return x.TradingPaused
	}
	return false
}

func (x *PositionAllocatorStatus) GetPauseReason() string {
	if x != nil {
		return x.PauseReason
	}
	return ""
}

type SignalReason struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Summary          string                   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Phase            string                   `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	TrendContext     string                   `protobuf:"bytes,3,opt,name=trend_context,json=trendContext,proto3" json:"trend_context,omitempty"`
	SetupContext     string                   `protobuf:"bytes,4,opt,name=setup_context,json=setupContext,proto3" json:"setup_context,omitempty"`
	PathContext      string                   `protobuf:"bytes,5,opt,name=path_context,json=pathContext,proto3" json:"path_context,omitempty"`
	ExecutionContext string                   `protobuf:"bytes,6,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	Tags             []string                 `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	RouteBucket      string                   `protobuf:"bytes,8,opt,name=route_bucket,json=routeBucket,proto3" json:"route_bucket,omitempty"`
	RouteReason      string                   `protobuf:"bytes,9,opt,name=route_reason,json=routeReason,proto3" json:"route_reason,omitempty"`
	RouteTemplate    string                   `protobuf:"bytes,10,opt,name=route_template,json=routeTemplate,proto3" json:"route_template,omitempty"`
	Allocator        *PositionAllocatorStatus `protobuf:"bytes,11,opt,name=allocator,proto3" json:"allocator,omitempty"`
	Range            *RangeSignalReason       `protobuf:"bytes,12,opt,name=range,proto3" json:"range,omitempty"`
	ExitReasonKind   string                   `protobuf:"bytes,13,opt,name=exit_reason_kind,json=exitReasonKind,proto3" json:"exit_reason_kind,omitempty"`
	ExitReasonLabel  string                   `protobuf:"bytes,14,opt,name=exit_reason_label,json=exitReasonLabel,proto3" json:"exit_reason_label,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignalReason) Reset() {
	*x = SignalReason{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalReason) ProtoMessage() {}

func (x *SignalReason) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalReason.ProtoReflect.Descriptor instead.
func (*SignalReason) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *SignalReason) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SignalReason) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SignalReason) GetTrendContext() string {
	if x != nil {
		return x.TrendContext
	}
	return ""
}

func (x *SignalReason) GetSetupContext() string {
	if x != nil {
		return x.SetupContext
	}
	return ""
}

func (x *SignalReason) GetPathContext() string {
	if x != nil {
		return x.PathContext
	}
	return ""
}

func (x *SignalReason) GetExecutionContext() string {
	if x != nil {
		return x.ExecutionContext
	}
	return ""
}

func (x *SignalReason) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SignalReason) GetRouteBucket() string {
	if x != nil {
		return x.RouteBucket
	}
	return ""
}

func (x *SignalReason) GetRouteReason() string {
	if x != nil {
		return x.RouteReason
	}
	return ""
}

func (x *SignalReason) GetRouteTemplate() string {
	if x != nil {
		return x.RouteTemplate
	}
	return ""
}

func (x *SignalReason) GetAllocator() *PositionAllocatorStatus {
	if x != nil {
		return x.Allocator
	}
	return nil
}

func (x *SignalReason) GetRange() *RangeSignalReason {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *SignalReason) GetExitReasonKind() string {
	if x != nil {
		return x.ExitReasonKind
	}
	return ""
}

func (x *SignalReason) GetExitReasonLabel() string {
	if x != nil {
		return x.ExitReasonLabel
	}
	return ""
}

type RangeSignalReason struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	H1RangeOk      bool                   `protobuf:"varint,1,opt,name=h1_range_ok,json=h1RangeOk,proto3" json:"h1_range_ok,omitempty"`
	H1AdxOk        bool                   `protobuf:"varint,2,opt,name=h1_adx_ok,json=h1AdxOk,proto3" json:"h1_adx_ok,omitempty"`
	H1BollWidthOk  bool                   `protobuf:"varint,3,opt,name=h1_boll_width_ok,json=h1BollWidthOk,proto3" json:"h1_boll_width_ok,omitempty"`
	M15TouchLower  bool                   `protobuf:"varint,4,opt,name=m15_touch_lower,json=m15TouchLower,proto3" json:"m15_touch_lower,omitempty"`
	M15RsiTurnUp   bool                   `protobuf:"varint,5,opt,name=m15_rsi_turn_up,json=m15RsiTurnUp,proto3" json:"m15_rsi_turn_up,omitempty"`
	M15TouchUpper  bool                   `protobuf:"varint,6,opt,name=m15_touch_upper,json=m15TouchUpper,proto3" json:"m15_touch_upper,omitempty"`
	M15RsiTurnDown bool                   `protobuf:"varint,7,opt,name=m15_rsi_turn_down,json=m15RsiTurnDown,proto3" json:"m15_rsi_turn_down,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RangeSignalReason) Reset() {
	*x = RangeSignalReason{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSignalReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSignalReason) ProtoMessage() {}

func (x *RangeSignalReason) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSignalReason.ProtoReflect.Descriptor instead.
func (*RangeSignalReason) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *RangeSignalReason) GetH1RangeOk() bool {
	if x != nil {
		return x.H1RangeOk
	}
	return false
}

func (x *RangeSignalReason) GetH1AdxOk() bool {
	if x != nil {
		return x.H1AdxOk
	}
	return false
}

func (x *RangeSignalReason) GetH1BollWidthOk() bool {
	if x != nil {
		return x.H1BollWidthOk
	}
	return false
}

func (x *RangeSignalReason) GetM15TouchLower() bool {
	if x != nil {
		return x.M15TouchLower
	}
	return false
}

func (x *RangeSignalReason) GetM15RsiTurnUp() bool {
	if x != nil {
		return x.M15RsiTurnUp
	}
	return false
}

func (x *RangeSignalReason) GetM15TouchUpper() bool {
	if x != nil {
		return x.M15TouchUpper
	}
	return false
}

func (x *RangeSignalReason) GetM15RsiTurnDown() bool {
	if x != nil {
		return x.M15RsiTurnDown
	}
	return false
}

type ProtectionLegStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requested     bool                   `protobuf:"varint,1,opt,name=requested,proto3" json:"requested,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TriggerPrice  float64                `protobuf:"fixed64,3,opt,name=trigger_price,json=triggerPrice,proto3" json:"trigger_price,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	OrderId       string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,6,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtectionLegStatus) Reset() {
	*x = ProtectionLegStatus{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectionLegStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectionLegStatus) ProtoMessage() {}

func (x *ProtectionLegStatus) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectionLegStatus.ProtoReflect.Descriptor instead.
func (*ProtectionLegStatus) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *ProtectionLegStatus) GetRequested() bool {
	if x != nil {
		return x.Requested
	}
	return false
}

func (x *ProtectionLegStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProtectionLegStatus) GetTriggerPrice() float64 {
	if x != nil {
		return x.TriggerPrice
	}
	return 0
}

func (x *ProtectionLegStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProtectionLegStatus) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProtectionLegStatus) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

type ProtectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requested     bool                   `protobuf:"varint,1,opt,name=requested,proto3" json:"requested,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	StopLoss      *ProtectionLegStatus   `protobuf:"bytes,4,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	TakeProfit    *ProtectionLegStatus   `protobuf:"bytes,5,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtectionStatus) Reset() {
	*x = ProtectionStatus{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectionStatus) ProtoMessage() {}

func (x *ProtectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectionStatus.ProtoReflect.Descriptor instead.
func (*ProtectionStatus) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *ProtectionStatus) GetRequested() bool {
	if x != nil {
		return x.Requested
	}
	return false
}

func (x *ProtectionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProtectionStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProtectionStatus) GetStopLoss() *ProtectionLegStatus {
	if x != nil {
		return x.StopLoss
	}
	return nil
}

func (x *ProtectionStatus) GetTakeProfit() *ProtectionLegStatus {
	if x != nil {
		return x.TakeProfit
	}
	return nil
}

type AllOrderItem struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	OrderId                     int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol                      string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Status                      string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Side                        string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	PositionSide                string                 `protobuf:"bytes,5,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"`
	Type                        string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	OrigQty                     string                 `protobuf:"bytes,7,opt,name=orig_qty,json=origQty,proto3" json:"orig_qty,omitempty"`
	ExecutedQty                 string                 `protobuf:"bytes,8,opt,name=executed_qty,json=executedQty,proto3" json:"executed_qty,omitempty"`
	AvgPrice                    string                 `protobuf:"bytes,9,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Price                       string                 `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty"`
	StopPrice                   string                 `protobuf:"bytes,11,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	ClientOrderId               string                 `protobuf:"bytes,12,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Time                        int64                  `protobuf:"varint,13,opt,name=time,proto3" json:"time,omitempty"`
	UpdateTime                  int64                  `protobuf:"varint,14,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ReduceOnly                  bool                   `protobuf:"varint,15,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	ClosePosition               bool                   `protobuf:"varint,16,opt,name=close_position,json=closePosition,proto3" json:"close_position,omitempty"`
	TimeInForce                 string                 `protobuf:"bytes,17,opt,name=time_in_force,json=timeInForce,proto3" json:"time_in_force,omitempty"`
	EstimatedFee                string                 `protobuf:"bytes,18,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`
	ActualFee                   string                 `protobuf:"bytes,19,opt,name=actual_fee,json=actualFee,proto3" json:"actual_fee,omitempty"`
	ActualFeeAsset              string                 `protobuf:"bytes,20,opt,name=actual_fee_asset,json=actualFeeAsset,proto3" json:"actual_fee_asset,omitempty"`
	ActionType                  string                 `protobuf:"bytes,21,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	PositionCycleId             string                 `protobuf:"bytes,22,opt,name=position_cycle_id,json=positionCycleId,proto3" json:"position_cycle_id,omitempty"`
	HarvestPathProbability      string                 `protobuf:"bytes,23,opt,name=harvest_path_probability,json=harvestPathProbability,proto3" json:"harvest_path_probability,omitempty"`
	HarvestPathAction           string                 `protobuf:"bytes,24,opt,name=harvest_path_action,json=harvestPathAction,proto3" json:"harvest_path_action,omitempty"`
	HarvestPathRiskLevel        string                 `protobuf:"bytes,25,opt,name=harvest_path_risk_level,json=harvestPathRiskLevel,proto3" json:"harvest_path_risk_level,omitempty"`
	HarvestPathTargetSide       string                 `protobuf:"bytes,26,opt,name=harvest_path_target_side,json=harvestPathTargetSide,proto3" json:"harvest_path_target_side,omitempty"`
	HarvestPathReferencePrice   string                 `protobuf:"bytes,27,opt,name=harvest_path_reference_price,json=harvestPathReferencePrice,proto3" json:"harvest_path_reference_price,omitempty"`
	HarvestPathMarketPrice      string                 `protobuf:"bytes,28,opt,name=harvest_path_market_price,json=harvestPathMarketPrice,proto3" json:"harvest_path_market_price,omitempty"`
	Reason                      string                 `protobuf:"bytes,29,opt,name=reason,proto3" json:"reason,omitempty"`
	SignalReason                *SignalReason          `protobuf:"bytes,30,opt,name=signal_reason,json=signalReason,proto3" json:"signal_reason,omitempty"`
	HarvestPathLstmProbability  string                 `protobuf:"bytes,31,opt,name=harvest_path_lstm_probability,json=harvestPathLstmProbability,proto3" json:"harvest_path_lstm_probability,omitempty"`
	HarvestPathRuleProbability  string                 `protobuf:"bytes,32,opt,name=harvest_path_rule_probability,json=harvestPathRuleProbability,proto3" json:"harvest_path_rule_probability,omitempty"`
	HarvestPathVolatilityRegime string                 `protobuf:"bytes,33,opt,name=harvest_path_volatility_regime,json=harvestPathVolatilityRegime,proto3" json:"harvest_path_volatility_regime,omitempty"`
	HarvestPathThresholdSource  string                 `protobuf:"bytes,34,opt,name=harvest_path_threshold_source,json=harvestPathThresholdSource,proto3" json:"harvest_path_threshold_source,omitempty"`
	HarvestPathAppliedThreshold string                 `protobuf:"bytes,35,opt,name=harvest_path_applied_threshold,json=harvestPathAppliedThreshold,proto3" json:"harvest_path_applied_threshold,omitempty"`
	HarvestPathBookProbability  string                 `protobuf:"bytes,36,opt,name=harvest_path_book_probability,json=harvestPathBookProbability,proto3" json:"harvest_path_book_probability,omitempty"`
	HarvestPathBookSummary      string                 `protobuf:"bytes,37,opt,name=harvest_path_book_summary,json=harvestPathBookSummary,proto3" json:"harvest_path_book_summary,omitempty"`
	Protection                  *ProtectionStatus      `protobuf:"bytes,38,opt,name=protection,proto3" json:"protection,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AllOrderItem) Reset() {
	*x = AllOrderItem{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllOrderItem) ProtoMessage() {}

func (x *AllOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllOrderItem.ProtoReflect.Descriptor instead.
func (*AllOrderItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *AllOrderItem) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *AllOrderItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AllOrderItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AllOrderItem) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *AllOrderItem) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

func (x *AllOrderItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AllOrderItem) GetOrigQty() string {
	if x != nil {
		return x.OrigQty
	}
	return ""
}

func (x *AllOrderItem) GetExecutedQty() string {
	if x != nil {
		return x.ExecutedQty
	}
	return ""
}

func (x *AllOrderItem) GetAvgPrice() string {
	if x != nil {
		return x.AvgPrice
	}
	return ""
}

func (x *AllOrderItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *AllOrderItem) GetStopPrice() string {
	if x != nil {
		return x.StopPrice
	}
	return ""
}

func (x *AllOrderItem) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *AllOrderItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *AllOrderItem) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *AllOrderItem) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *AllOrderItem) GetClosePosition() bool {
	if x != nil {
		return x.ClosePosition
	}
	return false
}

func (x *AllOrderItem) GetTimeInForce() string {
	if x != nil {
		return x.TimeInForce
	}
	return ""
}

func (x *AllOrderItem) GetEstimatedFee() string {
	if x != nil {
		return x.EstimatedFee
	}
	return ""
}

func (x *AllOrderItem) GetActualFee() string {
	if x != nil {
		return x.ActualFee
	}
	return ""
}

func (x *AllOrderItem) GetActualFeeAsset() string {
	if x != nil {
		return x.ActualFeeAsset
	}
	return ""
}

func (x *AllOrderItem) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *AllOrderItem) GetPositionCycleId() string {
	if x != nil {
		return x.PositionCycleId
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathProbability() string {
	if x != nil {
		return x.HarvestPathProbability
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathAction() string {
	if x != nil {
		return x.HarvestPathAction
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathRiskLevel() string {
	if x != nil {
		return x.HarvestPathRiskLevel
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathTargetSide() string {
	if x != nil {
		return x.HarvestPathTargetSide
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathReferencePrice() string {
	if x != nil {
		return x.HarvestPathReferencePrice
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathMarketPrice() string {
	if x != nil {
		return x.HarvestPathMarketPrice
	}
	return ""
}

func (x *AllOrderItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AllOrderItem) GetSignalReason() *SignalReason {
	if x != nil {
		return x.SignalReason
	}
	return nil
}

func (x *AllOrderItem) GetHarvestPathLstmProbability() string {
	if x != nil {
		return x.HarvestPathLstmProbability
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathRuleProbability() string {
	if x != nil {
		return x.HarvestPathRuleProbability
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathVolatilityRegime() string {
	if x != nil {
		return x.HarvestPathVolatilityRegime
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathThresholdSource() string {
	if x != nil {
		return x.HarvestPathThresholdSource
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathAppliedThreshold() string {
	if x != nil {
		return x.HarvestPathAppliedThreshold
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathBookProbability() string {
	if x != nil {
		return x.HarvestPathBookProbability
	}
	return ""
}

func (x *AllOrderItem) GetHarvestPathBookSummary() string {
	if x != nil {
		return x.HarvestPathBookSummary
	}
	return ""
}

func (x *AllOrderItem) GetProtection() *ProtectionStatus {
	if x != nil {
		return x.Protection
	}
	return nil
}

// 历史成交条目
type UserTradeItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol          string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId         int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Side            string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`
	PositionSide    string                 `protobuf:"bytes,5,opt,name=position_side,json=positionSide,proto3" json:"position_side,omitempty"`
	Price           string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Qty             string                 `protobuf:"bytes,7,opt,name=qty,proto3" json:"qty,omitempty"`
	RealizedPnl     string                 `protobuf:"bytes,8,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	MarginAsset     string                 `protobuf:"bytes,9,opt,name=margin_asset,json=marginAsset,proto3" json:"margin_asset,omitempty"`
	QuoteQty        string                 `protobuf:"bytes,10,opt,name=quote_qty,json=quoteQty,proto3" json:"quote_qty,omitempty"`
	Commission      string                 `protobuf:"bytes,11,opt,name=commission,proto3" json:"commission,omitempty"`
	CommissionAsset string                 `protobuf:"bytes,12,opt,name=commission_asset,json=commissionAsset,proto3" json:"commission_asset,omitempty"`
	Time            int64                  `protobuf:"varint,13,opt,name=time,proto3" json:"time,omitempty"`
	Buyer           bool                   `protobuf:"varint,14,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Maker           bool                   `protobuf:"varint,15,opt,name=maker,proto3" json:"maker,omitempty"`
	EstimatedFee    string                 `protobuf:"bytes,16,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`
	ActualFee       string                 `protobuf:"bytes,17,opt,name=actual_fee,json=actualFee,proto3" json:"actual_fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserTradeItem) Reset() {
	*x = UserTradeItem{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTradeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTradeItem) ProtoMessage() {}

func (x *UserTradeItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTradeItem.ProtoReflect.Descriptor instead.
func (*UserTradeItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *UserTradeItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserTradeItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *UserTradeItem) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UserTradeItem) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *UserTradeItem) GetPositionSide() string {
	if x != nil {
		return x.PositionSide
	}
	return ""
}

func (x *UserTradeItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *UserTradeItem) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *UserTradeItem) GetRealizedPnl() string {
	if x != nil {
		return x.RealizedPnl
	}
	return ""
}

func (x *UserTradeItem) GetMarginAsset() string {
	if x != nil {
		return x.MarginAsset
	}
	return ""
}

func (x *UserTradeItem) GetQuoteQty() string {
	if x != nil {
		return x.QuoteQty
	}
	return ""
}

func (x *UserTradeItem) GetCommission() string {
	if x != nil {
		return x.Commission
	}
	return ""
}

func (x *UserTradeItem) GetCommissionAsset() string {
	if x != nil {
		return x.CommissionAsset
	}
	return ""
}

func (x *UserTradeItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *UserTradeItem) GetBuyer() bool {
	if x != nil {
		return x.Buyer
	}
	return false
}

func (x *UserTradeItem) GetMaker() bool {
	if x != nil {
		return x.Maker
	}
	return false
}

func (x *UserTradeItem) GetEstimatedFee() string {
	if x != nil {
		return x.EstimatedFee
	}
	return ""
}

func (x *UserTradeItem) GetActualFee() string {
	if x != nil {
		return x.ActualFee
	}
	return ""
}

// 资金流水条目
type IncomeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	IncomeType    string                 `protobuf:"bytes,2,opt,name=income_type,json=incomeType,proto3" json:"income_type,omitempty"`
	Income        string                 `protobuf:"bytes,3,opt,name=income,proto3" json:"income,omitempty"`
	Asset         string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Time          int64                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	TranId        int64                  `protobuf:"varint,6,opt,name=tran_id,json=tranId,proto3" json:"tran_id,omitempty"`
	TradeId       string                 `protobuf:"bytes,7,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomeItem) Reset() {
	*x = IncomeItem{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeItem) ProtoMessage() {}

func (x *IncomeItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeItem.ProtoReflect.Descriptor instead.
func (*IncomeItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *IncomeItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IncomeItem) GetIncomeType() string {
	if x != nil {
		return x.IncomeType
	}
	return ""
}

func (x *IncomeItem) GetIncome() string {
	if x != nil {
		return x.Income
	}
	return ""
}

func (x *IncomeItem) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *IncomeItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *IncomeItem) GetTranId() int64 {
	if x != nil {
		return x.TranId
	}
	return 0
}

func (x *IncomeItem) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

// 资金费率条目
type FundingRateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	FundingRate   string                 `protobuf:"bytes,2,opt,name=funding_rate,json=fundingRate,proto3" json:"funding_rate,omitempty"`
	FundingTime   int64                  `protobuf:"varint,3,opt,name=funding_time,json=fundingTime,proto3" json:"funding_time,omitempty"`
	MarkPrice     string                 `protobuf:"bytes,4,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundingRateItem) Reset() {
	*x = FundingRateItem{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingRateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingRateItem) ProtoMessage() {}

func (x *FundingRateItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingRateItem.ProtoReflect.Descriptor instead.
func (*FundingRateItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *FundingRateItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FundingRateItem) GetFundingRate() string {
	if x != nil {
		return x.FundingRate
	}
	return ""
}

func (x *FundingRateItem) GetFundingTime() int64 {
	if x != nil {
		return x.FundingTime
	}
	return 0
}

func (x *FundingRateItem) GetMarkPrice() string {
	if x != nil {
		return x.MarkPrice
	}
	return ""
}

// 资金费用条目
type FundingFeeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	IncomeType    string                 `protobuf:"bytes,2,opt,name=income_type,json=incomeType,proto3" json:"income_type,omitempty"`
	Income        string                 `protobuf:"bytes,3,opt,name=income,proto3" json:"income,omitempty"`
	Asset         string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Time          int64                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	TranId        int64                  `protobuf:"varint,6,opt,name=tran_id,json=tranId,proto3" json:"tran_id,omitempty"`
	TradeId       string                 `protobuf:"bytes,7,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundingFeeItem) Reset() {
	*x = FundingFeeItem{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingFeeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingFeeItem) ProtoMessage() {}

func (x *FundingFeeItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingFeeItem.ProtoReflect.Descriptor instead.
func (*FundingFeeItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *FundingFeeItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FundingFeeItem) GetIncomeType() string {
	if x != nil {
		return x.IncomeType
	}
	return ""
}

func (x *FundingFeeItem) GetIncome() string {
	if x != nil {
		return x.Income
	}
	return ""
}

func (x *FundingFeeItem) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *FundingFeeItem) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *FundingFeeItem) GetTranId() int64 {
	if x != nil {
		return x.TranId
	}
	return 0
}

func (x *FundingFeeItem) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

// 通用列表响应
type OpenOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OpenOrderItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenOrderResponse) Reset() {
	*x = OpenOrderResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrderResponse) ProtoMessage() {}

func (x *OpenOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrderResponse.ProtoReflect.Descriptor instead.
func (*OpenOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *OpenOrderResponse) GetItems() []*OpenOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type AllOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AllOrderItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllOrderResponse) Reset() {
	*x = AllOrderResponse{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllOrderResponse) ProtoMessage() {}

func (x *AllOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllOrderResponse.ProtoReflect.Descriptor instead.
func (*AllOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *AllOrderResponse) GetItems() []*AllOrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UserTradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserTradeItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTradeResponse) Reset() {
	*x = UserTradeResponse{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTradeResponse) ProtoMessage() {}

func (x *UserTradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTradeResponse.ProtoReflect.Descriptor instead.
func (*UserTradeResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *UserTradeResponse) GetItems() []*UserTradeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type IncomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*IncomeItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomeResponse) Reset() {
	*x = IncomeResponse{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeResponse) ProtoMessage() {}

func (x *IncomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeResponse.ProtoReflect.Descriptor instead.
func (*IncomeResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *IncomeResponse) GetItems() []*IncomeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type FundingRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FundingRateItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundingRateResponse) Reset() {
	*x = FundingRateResponse{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingRateResponse) ProtoMessage() {}

func (x *FundingRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingRateResponse.ProtoReflect.Descriptor instead.
func (*FundingRateResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *FundingRateResponse) GetItems() []*FundingRateItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type FundingFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FundingFeeItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundingFeeResponse) Reset() {
	*x = FundingFeeResponse{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingFeeResponse) ProtoMessage() {}

func (x *FundingFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingFeeResponse.ProtoReflect.Descriptor instead.
func (*FundingFeeResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *FundingFeeResponse) GetItems() []*FundingFeeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 通用空请求
type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{18}
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"\x9c\x01\n" +
	"\x11OrderQueryRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vincome_type\x18\x05 \x01(\tR\n" +
	"incomeType\"\x80\x04\n" +
	"\rOpenOrderItem\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12#\n" +
	"\rposition_side\x18\x05 \x01(\tR\fpositionSide\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x19\n" +
	"\borig_qty\x18\a \x01(\tR\aorigQty\x12!\n" +
	"\fexecuted_qty\x18\b \x01(\tR\vexecutedQty\x12\x1b\n" +
	"\tavg_price\x18\t \x01(\tR\bavgPrice\x12\x14\n" +
	"\x05price\x18\n" +
	" \x01(\tR\x05price\x12\x1d\n" +
	"\n" +
	"stop_price\x18\v \x01(\tR\tstopPrice\x12&\n" +
	"\x0fclient_order_id\x18\f \x01(\tR\rclientOrderId\x12\x12\n" +
	"\x04time\x18\r \x01(\x03R\x04time\x12\x1f\n" +
	"\vupdate_time\x18\x0e \x01(\x03R\n" +
	"updateTime\x12\x1f\n" +
	"\vreduce_only\x18\x0f \x01(\bR\n" +
	"reduceOnly\x12%\n" +
	"\x0eclose_position\x18\x10 \x01(\bR\rclosePosition\x12\"\n" +
	"\rtime_in_force\x18\x11 \x01(\tR\vtimeInForce\"\xb9\x03\n" +
	"\x17PositionAllocatorStatus\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12!\n" +
	"\froute_bucket\x18\x02 \x01(\tR\vrouteBucket\x12!\n" +
	"\froute_reason\x18\x03 \x01(\tR\vrouteReason\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12!\n" +
	"\fscore_source\x18\x05 \x01(\tR\vscoreSource\x12#\n" +
	"\rbucket_budget\x18\x06 \x01(\x01R\fbucketBudget\x12'\n" +
	"\x0fstrategy_weight\x18\a \x01(\x01R\x0estrategyWeight\x12#\n" +
	"\rsymbol_weight\x18\b \x01(\x01R\fsymbolWeight\x12\x1d\n" +
	"\n" +
	"risk_scale\x18\t \x01(\x01R\triskScale\x12'\n" +
	"\x0fposition_budget\x18\n" +
	" \x01(\x01R\x0epositionBudget\x12%\n" +
	"\x0etrading_paused\x18\v \x01(\bR\rtradingPaused\x12!\n" +
	"\fpause_reason\x18\f \x01(\tR\vpauseReason\"\x9d\x04\n" +
	"\fSignalReason\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12#\n" +
	"\rtrend_context\x18\x03 \x01(\tR\ftrendContext\x12#\n" +
	"\rsetup_context\x18\x04 \x01(\tR\fsetupContext\x12!\n" +
	"\fpath_context\x18\x05 \x01(\tR\vpathContext\x12+\n" +
	"\x11execution_context\x18\x06 \x01(\tR\x10executionContext\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12!\n" +
	"\froute_bucket\x18\b \x01(\tR\vrouteBucket\x12!\n" +
	"\froute_reason\x18\t \x01(\tR\vrouteReason\x12%\n" +
	"\x0eroute_template\x18\n" +
	" \x01(\tR\rrouteTemplate\x12<\n" +
	"\tallocator\x18\v \x01(\v2\x1e.order.PositionAllocatorStatusR\tallocator\x12.\n" +
	"\x05range\x18\f \x01(\v2\x18.order.RangeSignalReasonR\x05range\x12(\n" +
	"\x10exit_reason_kind\x18\r \x01(\tR\x0eexitReasonKind\x12*\n" +
	"\x11exit_reason_label\x18\x0e \x01(\tR\x0fexitReasonLabel\"\x9a\x02\n" +
	"\x11RangeSignalReason\x12\x1e\n" +
	"\vh1_range_ok\x18\x01 \x01(\bR\th1RangeOk\x12\x1a\n" +
	"\th1_adx_ok\x18\x02 \x01(\bR\ah1AdxOk\x12'\n" +
	"\x10h1_boll_width_ok\x18\x03 \x01(\bR\rh1BollWidthOk\x12&\n" +
	"\x0fm15_touch_lower\x18\x04 \x01(\bR\rm15TouchLower\x12%\n" +
	"\x0fm15_rsi_turn_up\x18\x05 \x01(\bR\fm15RsiTurnUp\x12&\n" +
	"\x0fm15_touch_upper\x18\x06 \x01(\bR\rm15TouchUpper\x12)\n" +
	"\x11m15_rsi_turn_down\x18\a \x01(\bR\x0em15RsiTurnDown\"\xcb\x01\n" +
	"\x13ProtectionLegStatus\x12\x1c\n" +
	"\trequested\x18\x01 \x01(\bR\trequested\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rtrigger_price\x18\x03 \x01(\x01R\ftriggerPrice\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x06 \x01(\tR\rclientOrderId\"\xd6\x01\n" +
	"\x10ProtectionStatus\x12\x1c\n" +
	"\trequested\x18\x01 \x01(\bR\trequested\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x127\n" +
	"\tstop_loss\x18\x04 \x01(\v2\x1a.order.ProtectionLegStatusR\bstopLoss\x12;\n" +
	"\vtake_profit\x18\x05 \x01(\v2\x1a.order.ProtectionLegStatusR\n" +
	"takeProfit\"\xec\f\n" +
	"\fAllOrderItem\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12#\n" +
	"\rposition_side\x18\x05 \x01(\tR\fpositionSide\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x19\n" +
	"\borig_qty\x18\a \x01(\tR\aorigQty\x12!\n" +
	"\fexecuted_qty\x18\b \x01(\tR\vexecutedQty\x12\x1b\n" +
	"\tavg_price\x18\t \x01(\tR\bavgPrice\x12\x14\n" +
	"\x05price\x18\n" +
	" \x01(\tR\x05price\x12\x1d\n" +
	"\n" +
	"stop_price\x18\v \x01(\tR\tstopPrice\x12&\n" +
	"\x0fclient_order_id\x18\f \x01(\tR\rclientOrderId\x12\x12\n" +
	"\x04time\x18\r \x01(\x03R\x04time\x12\x1f\n" +
	"\vupdate_time\x18\x0e \x01(\x03R\n" +
	"updateTime\x12\x1f\n" +
	"\vreduce_only\x18\x0f \x01(\bR\n" +
	"reduceOnly\x12%\n" +
	"\x0eclose_position\x18\x10 \x01(\bR\rclosePosition\x12\"\n" +
	"\rtime_in_force\x18\x11 \x01(\tR\vtimeInForce\x12#\n" +
	"\restimated_fee\x18\x12 \x01(\tR\festimatedFee\x12\x1d\n" +
	"\n" +
	"actual_fee\x18\x13 \x01(\tR\tactualFee\x12(\n" +
	"\x10actual_fee_asset\x18\x14 \x01(\tR\x0eactualFeeAsset\x12\x1f\n" +
	"\vaction_type\x18\x15 \x01(\tR\n" +
	"actionType\x12*\n" +
	"\x11position_cycle_id\x18\x16 \x01(\tR\x0fpositionCycleId\x128\n" +
	"\x18harvest_path_probability\x18\x17 \x01(\tR\x16harvestPathProbability\x12.\n" +
	"\x13harvest_path_action\x18\x18 \x01(\tR\x11harvestPathAction\x125\n" +
	"\x17harvest_path_risk_level\x18\x19 \x01(\tR\x14harvestPathRiskLevel\x127\n" +
	"\x18harvest_path_target_side\x18\x1a \x01(\tR\x15harvestPathTargetSide\x12?\n" +
	"\x1charvest_path_reference_price\x18\x1b \x01(\tR\x19harvestPathReferencePrice\x129\n" +
	"\x19harvest_path_market_price\x18\x1c \x01(\tR\x16harvestPathMarketPrice\x12\x16\n" +
	"\x06reason\x18\x1d \x01(\tR\x06reason\x128\n" +
	"\rsignal_reason\x18\x1e \x01(\v2\x13.order.SignalReasonR\fsignalReason\x12A\n" +
	"\x1dharvest_path_lstm_probability\x18\x1f \x01(\tR\x1aharvestPathLstmProbability\x12A\n" +
	"\x1dharvest_path_rule_probability\x18  \x01(\tR\x1aharvestPathRuleProbability\x12C\n" +
	"\x1eharvest_path_volatility_regime\x18! \x01(\tR\x1bharvestPathVolatilityRegime\x12A\n" +
	"\x1dharvest_path_threshold_source\x18\" \x01(\tR\x1aharvestPathThresholdSource\x12C\n" +
	"\x1eharvest_path_applied_threshold\x18# \x01(\tR\x1bharvestPathAppliedThreshold\x12A\n" +
	"\x1dharvest_path_book_probability\x18$ \x01(\tR\x1aharvestPathBookProbability\x129\n" +
	"\x19harvest_path_book_summary\x18% \x01(\tR\x16harvestPathBookSummary\x127\n" +
	"\n" +
	"protection\x18& \x01(\v2\x17.order.ProtectionStatusR\n" +
	"protection\"\xe5\x03\n" +
	"\rUserTradeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12#\n" +
	"\rposition_side\x18\x05 \x01(\tR\fpositionSide\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x10\n" +
	"\x03qty\x18\a \x01(\tR\x03qty\x12!\n" +
	"\frealized_pnl\x18\b \x01(\tR\vrealizedPnl\x12!\n" +
	"\fmargin_asset\x18\t \x01(\tR\vmarginAsset\x12\x1b\n" +
	"\tquote_qty\x18\n" +
	" \x01(\tR\bquoteQty\x12\x1e\n" +
	"\n" +
	"commission\x18\v \x01(\tR\n" +
	"commission\x12)\n" +
	"\x10commission_asset\x18\f \x01(\tR\x0fcommissionAsset\x12\x12\n" +
	"\x04time\x18\r \x01(\x03R\x04time\x12\x14\n" +
	"\x05buyer\x18\x0e \x01(\bR\x05buyer\x12\x14\n" +
	"\x05maker\x18\x0f \x01(\bR\x05maker\x12#\n" +
	"\restimated_fee\x18\x10 \x01(\tR\festimatedFee\x12\x1d\n" +
	"\n" +
	"actual_fee\x18\x11 \x01(\tR\tactualFee\"\xbb\x01\n" +
	"\n" +
	"IncomeItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vincome_type\x18\x02 \x01(\tR\n" +
	"incomeType\x12\x16\n" +
	"\x06income\x18\x03 \x01(\tR\x06income\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x03R\x04time\x12\x17\n" +
	"\atran_id\x18\x06 \x01(\x03R\x06tranId\x12\x19\n" +
	"\btrade_id\x18\a \x01(\tR\atradeId\"\x8e\x01\n" +
	"\x0fFundingRateItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\ffunding_rate\x18\x02 \x01(\tR\vfundingRate\x12!\n" +
	"\ffunding_time\x18\x03 \x01(\x03R\vfundingTime\x12\x1d\n" +
	"\n" +
	"mark_price\x18\x04 \x01(\tR\tmarkPrice\"\xbf\x01\n" +
	"\x0eFundingFeeItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vincome_type\x18\x02 \x01(\tR\n" +
	"incomeType\x12\x16\n" +
	"\x06income\x18\x03 \x01(\tR\x06income\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x03R\x04time\x12\x17\n" +
	"\atran_id\x18\x06 \x01(\x03R\x06tranId\x12\x19\n" +
	"\btrade_id\x18\a \x01(\tR\atradeId\"?\n" +
	"\x11OpenOrderResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.order.OpenOrderItemR\x05items\"=\n" +
	"\x10AllOrderResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.order.AllOrderItemR\x05items\"?\n" +
	"\x11UserTradeResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.order.UserTradeItemR\x05items\"9\n" +
	"\x0eIncomeResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.order.IncomeItemR\x05items\"C\n" +
	"\x13FundingRateResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.order.FundingRateItemR\x05items\"A\n" +
	"\x12FundingFeeResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.order.FundingFeeItemR\x05items\"\x0e\n" +
	"\fEmptyRequest2\x83\x04\n" +
	"\fOrderService\x12E\n" +
	"\rGetOpenOrders\x12\x18.order.OrderQueryRequest\x1a\x18.order.OpenOrderResponse\"\x00\x12C\n" +
	"\fGetAllOrders\x12\x18.order.OrderQueryRequest\x1a\x17.order.AllOrderResponse\"\x00\x12E\n" +
	"\rGetUserTrades\x12\x18.order.OrderQueryRequest\x1a\x18.order.UserTradeResponse\"\x00\x12E\n" +
	"\x10GetIncomeHistory\x12\x18.order.OrderQueryRequest\x1a\x15.order.IncomeResponse\"\x00\x12O\n" +
	"\x15GetFundingRateHistory\x12\x18.order.OrderQueryRequest\x1a\x1a.order.FundingRateResponse\"\x00\x12G\n" +
	"\x0eGetFundingFees\x12\x18.order.OrderQueryRequest\x1a\x19.order.FundingFeeResponse\"\x00\x12?\n" +
	"\fFetchAllData\x12\x18.order.OrderQueryRequest\x1a\x13.order.EmptyRequest\"\x00B!Z\x1fexchange-system/common/pb/orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_order_proto_goTypes = []any{
	(*OrderQueryRequest)(nil),       // 0: order.OrderQueryRequest
	(*OpenOrderItem)(nil),           // 1: order.OpenOrderItem
	(*PositionAllocatorStatus)(nil), // 2: order.PositionAllocatorStatus
	(*SignalReason)(nil),            // 3: order.SignalReason
	(*RangeSignalReason)(nil),       // 4: order.RangeSignalReason
	(*ProtectionLegStatus)(nil),     // 5: order.ProtectionLegStatus
	(*ProtectionStatus)(nil),        // 6: order.ProtectionStatus
	(*AllOrderItem)(nil),            // 7: order.AllOrderItem
	(*UserTradeItem)(nil),           // 8: order.UserTradeItem
	(*IncomeItem)(nil),              // 9: order.IncomeItem
	(*FundingRateItem)(nil),         // 10: order.FundingRateItem
	(*FundingFeeItem)(nil),          // 11: order.FundingFeeItem
	(*OpenOrderResponse)(nil),       // 12: order.OpenOrderResponse
	(*AllOrderResponse)(nil),        // 13: order.AllOrderResponse
	(*UserTradeResponse)(nil),       // 14: order.UserTradeResponse
	(*IncomeResponse)(nil),          // 15: order.IncomeResponse
	(*FundingRateResponse)(nil),     // 16: order.FundingRateResponse
	(*FundingFeeResponse)(nil),      // 17: order.FundingFeeResponse
	(*EmptyRequest)(nil),            // 18: order.EmptyRequest
}
var file_order_proto_depIdxs = []int32{
	2,  // 0: order.SignalReason.allocator:type_name -> order.PositionAllocatorStatus
	4,  // 1: order.SignalReason.range:type_name -> order.RangeSignalReason
	5,  // 2: order.ProtectionStatus.stop_loss:type_name -> order.ProtectionLegStatus
	5,  // 3: order.ProtectionStatus.take_profit:type_name -> order.ProtectionLegStatus
	3,  // 4: order.AllOrderItem.signal_reason:type_name -> order.SignalReason
	6,  // 5: order.AllOrderItem.protection:type_name -> order.ProtectionStatus
	1,  // 6: order.OpenOrderResponse.items:type_name -> order.OpenOrderItem
	7,  // 7: order.AllOrderResponse.items:type_name -> order.AllOrderItem
	8,  // 8: order.UserTradeResponse.items:type_name -> order.UserTradeItem
	9,  // 9: order.IncomeResponse.items:type_name -> order.IncomeItem
	10, // 10: order.FundingRateResponse.items:type_name -> order.FundingRateItem
	11, // 11: order.FundingFeeResponse.items:type_name -> order.FundingFeeItem
	0,  // 12: order.OrderService.GetOpenOrders:input_type -> order.OrderQueryRequest
	0,  // 13: order.OrderService.GetAllOrders:input_type -> order.OrderQueryRequest
	0,  // 14: order.OrderService.GetUserTrades:input_type -> order.OrderQueryRequest
	0,  // 15: order.OrderService.GetIncomeHistory:input_type -> order.OrderQueryRequest
	0,  // 16: order.OrderService.GetFundingRateHistory:input_type -> order.OrderQueryRequest
	0,  // 17: order.OrderService.GetFundingFees:input_type -> order.OrderQueryRequest
	0,  // 18: order.OrderService.FetchAllData:input_type -> order.OrderQueryRequest
	12, // 19: order.OrderService.GetOpenOrders:output_type -> order.OpenOrderResponse
	13, // 20: order.OrderService.GetAllOrders:output_type -> order.AllOrderResponse
	14, // 21: order.OrderService.GetUserTrades:output_type -> order.UserTradeResponse
	15, // 22: order.OrderService.GetIncomeHistory:output_type -> order.IncomeResponse
	16, // 23: order.OrderService.GetFundingRateHistory:output_type -> order.FundingRateResponse
	17, // 24: order.OrderService.GetFundingFees:output_type -> order.FundingFeeResponse
	18, // 25: order.OrderService.FetchAllData:output_type -> order.EmptyRequest
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
