// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_GetOpenOrders_FullMethodName         = "/order.OrderService/GetOpenOrders"
	OrderService_GetAllOrders_FullMethodName          = "/order.OrderService/GetAllOrders"
	OrderService_GetUserTrades_FullMethodName         = "/order.OrderService/GetUserTrades"
	OrderService_GetIncomeHistory_FullMethodName      = "/order.OrderService/GetIncomeHistory"
	OrderService_GetFundingRateHistory_FullMethodName = "/order.OrderService/GetFundingRateHistory"
	OrderService_GetFundingFees_FullMethodName        = "/order.OrderService/GetFundingFees"
	OrderService_FetchAllData_FullMethodName          = "/order.OrderService/FetchAllData"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Order 服务
type OrderServiceClient interface {
	// 查询当前委托（未成交订单）
	GetOpenOrders(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*OpenOrderResponse, error)
	// 查询历史委托
	GetAllOrders(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*AllOrderResponse, error)
	// 查询历史成交
	GetUserTrades(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*UserTradeResponse, error)
	// 查询资金流水
	GetIncomeHistory(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*IncomeResponse, error)
	// 查询资金费率历史
	GetFundingRateHistory(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*FundingRateResponse, error)
	// 查询资金费用
	GetFundingFees(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*FundingFeeResponse, error)
	// 拉取全部数据并保存到本地 JSONL
	FetchAllData(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*EmptyRequest, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) GetOpenOrders(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*OpenOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_GetOpenOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetAllOrders(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*AllOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_GetAllOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetUserTrades(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*UserTradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserTradeResponse)
	err := c.cc.Invoke(ctx, OrderService_GetUserTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetIncomeHistory(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*IncomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncomeResponse)
	err := c.cc.Invoke(ctx, OrderService_GetIncomeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetFundingRateHistory(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*FundingRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FundingRateResponse)
	err := c.cc.Invoke(ctx, OrderService_GetFundingRateHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetFundingFees(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*FundingFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FundingFeeResponse)
	err := c.cc.Invoke(ctx, OrderService_GetFundingFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) FetchAllData(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*EmptyRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyRequest)
	err := c.cc.Invoke(ctx, OrderService_FetchAllData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
//
// Order 服务
type OrderServiceServer interface {
	// 查询当前委托（未成交订单）
	GetOpenOrders(context.Context, *OrderQueryRequest) (*OpenOrderResponse, error)
	// 查询历史委托
	GetAllOrders(context.Context, *OrderQueryRequest) (*AllOrderResponse, error)
	// 查询历史成交
	GetUserTrades(context.Context, *OrderQueryRequest) (*UserTradeResponse, error)
	// 查询资金流水
	GetIncomeHistory(context.Context, *OrderQueryRequest) (*IncomeResponse, error)
	// 查询资金费率历史
	GetFundingRateHistory(context.Context, *OrderQueryRequest) (*FundingRateResponse, error)
	// 查询资金费用
	GetFundingFees(context.Context, *OrderQueryRequest) (*FundingFeeResponse, error)
	// 拉取全部数据并保存到本地 JSONL
	FetchAllData(context.Context, *OrderQueryRequest) (*EmptyRequest, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) GetOpenOrders(context.Context, *OrderQueryRequest) (*OpenOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenOrders not implemented")
}
func (UnimplementedOrderServiceServer) GetAllOrders(context.Context, *OrderQueryRequest) (*AllOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllOrders not implemented")
}
func (UnimplementedOrderServiceServer) GetUserTrades(context.Context, *OrderQueryRequest) (*UserTradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTrades not implemented")
}
func (UnimplementedOrderServiceServer) GetIncomeHistory(context.Context, *OrderQueryRequest) (*IncomeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIncomeHistory not implemented")
}
func (UnimplementedOrderServiceServer) GetFundingRateHistory(context.Context, *OrderQueryRequest) (*FundingRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundingRateHistory not implemented")
}
func (UnimplementedOrderServiceServer) GetFundingFees(context.Context, *OrderQueryRequest) (*FundingFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundingFees not implemented")
}
func (UnimplementedOrderServiceServer) FetchAllData(context.Context, *OrderQueryRequest) (*EmptyRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchAllData not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_GetOpenOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOpenOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOpenOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOpenOrders(ctx, req.(*OrderQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetAllOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetAllOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetAllOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetAllOrders(ctx, req.(*OrderQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetUserTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetUserTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetUserTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetUserTrades(ctx, req.(*OrderQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetIncomeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetIncomeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetIncomeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetIncomeHistory(ctx, req.(*OrderQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetFundingRateHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetFundingRateHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetFundingRateHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetFundingRateHistory(ctx, req.(*OrderQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetFundingFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetFundingFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetFundingFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetFundingFees(ctx, req.(*OrderQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_FetchAllData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).FetchAllData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_FetchAllData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).FetchAllData(ctx, req.(*OrderQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOpenOrders",
			Handler:    _OrderService_GetOpenOrders_Handler,
		},
		{
			MethodName: "GetAllOrders",
			Handler:    _OrderService_GetAllOrders_Handler,
		},
		{
			MethodName: "GetUserTrades",
			Handler:    _OrderService_GetUserTrades_Handler,
		},
		{
			MethodName: "GetIncomeHistory",
			Handler:    _OrderService_GetIncomeHistory_Handler,
		},
		{
			MethodName: "GetFundingRateHistory",
			Handler:    _OrderService_GetFundingRateHistory_Handler,
		},
		{
			MethodName: "GetFundingFees",
			Handler:    _OrderService_GetFundingFees_Handler,
		},
		{
			MethodName: "FetchAllData",
			Handler:    _OrderService_FetchAllData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
