-- 为已存在的 exchange_analytics 表补充字段备注。
-- 该脚本用于增量迁移，不替代初始化脚本。

ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN event_time '事件写入时间';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN symbol '交易对标识';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN interval 'K 线周期';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN open_time 'K 线开始时间';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN close_time 'K 线结束时间';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN open '开盘价';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN high '最高价';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN low '最低价';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN close '收盘价';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN volume '成交量';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN quote_volume '计价货币成交额';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN taker_buy_volume '主动买入成交量';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN is_closed 'K 线是否闭合';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN is_dirty '是否为脏数据';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN dirty_reason '脏数据原因';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN is_tradable '当前 K 线是否允许交易';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN is_final '指标与状态是否最终确定';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN ema21 '21 周期 EMA 指标值';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN ema55 '55 周期 EMA 指标值';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN rsi 'RSI 指标值';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN atr 'ATR 指标值';
ALTER TABLE exchange_analytics.kline_fact COMMENT COLUMN source '数据来源';

ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN event_time '决策事件时间';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN symbol '交易对标识';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN strategy_id '策略唯一标识';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN template '策略模板名称';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN interval '决策使用的 K 线周期';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN stage '决策阶段';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN decision '决策结果';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN reason '决策原因描述';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN reason_code '决策原因编码';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN has_position '当前是否持仓';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN is_final '决策结果是否最终确定';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN is_tradable '当前市场是否允许交易';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN open_time '关联 K 线开始时间';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN close_time '关联 K 线结束时间';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN route_bucket '决策路由分桶';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN route_reason '决策路由原因';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN extras_json '扩展上下文信息 JSON';
ALTER TABLE exchange_analytics.decision_fact COMMENT COLUMN trace_id '链路追踪标识';

ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN event_time '信号事件时间';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN symbol '交易对标识';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN strategy_id '策略唯一标识';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN template '策略模板名称';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN signal_id '信号唯一标识';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN action '信号动作';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN side '交易方向';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN signal_type '信号类型';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN quantity '计划下单数量';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN entry_price '期望入场价';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN stop_loss '止损价';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN take_profit_json '止盈配置 JSON';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN reason '信号触发原因描述';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN exit_reason_kind '退出原因分类';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN exit_reason_label '退出原因标签';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN risk_reward '风险收益比';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN atr '生成信号时的 ATR 值';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN tags_json '信号标签 JSON';
ALTER TABLE exchange_analytics.signal_fact COMMENT COLUMN trace_id '链路追踪标识';

ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN event_time '执行事件时间';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN account_id '账户唯一标识';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN symbol '交易对标识';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN strategy_id '策略唯一标识';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN signal_id '关联信号标识';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN order_id '交易所订单标识';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN client_order_id '客户端订单标识';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN action '执行动作';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN side '交易方向';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN signal_type '信号类型';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN requested_qty '请求执行数量';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN executed_qty '实际执行数量';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN price '执行价格';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN status '执行状态';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN exchange '交易所标识';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN latency_ms '执行延迟毫秒数';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN error_code '错误编码';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN error_message '错误信息';
ALTER TABLE exchange_analytics.execution_event_fact COMMENT COLUMN trace_id '链路追踪标识';

ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN event_time '订单事件时间';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN account_id '账户唯一标识';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN symbol '交易对标识';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN order_id '交易所订单标识';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN client_order_id '客户端订单标识';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN position_cycle_id '仓位周期标识';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN strategy_id '策略唯一标识';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN template '策略模板名称';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN action_type '订单动作类型';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN side '交易方向';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN order_type '订单类型';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN price '委托价格';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN orig_qty '原始委托数量';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN executed_qty '累计成交数量';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN status '订单状态';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN reduce_only '是否仅减仓';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN reason '订单原因描述';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN signal_reason_json '信号原因 JSON';
ALTER TABLE exchange_analytics.order_event_fact COMMENT COLUMN trace_id '链路追踪标识';

ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN open_time '仓位周期开始时间';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN close_time '仓位周期结束时间';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN account_id '账户唯一标识';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN symbol '交易对标识';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN position_cycle_id '仓位周期唯一标识';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN strategy_id '策略唯一标识';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN template '策略模板名称';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN position_side '持仓方向';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN cycle_status '仓位周期状态';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN entry_price '平均开仓价';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN exit_price '平均平仓价';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN entry_qty '累计开仓数量';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN exit_qty '累计平仓数量';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN realized_pnl '已实现盈亏';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN max_profit '周期内最大浮盈';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN max_drawdown '周期内最大回撤';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN partial_close_order_count '部分平仓订单数量';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN final_close_order_count '最终平仓订单数量';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN exit_reason_kind '退出原因分类';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN exit_reason_label '退出原因标签';
ALTER TABLE exchange_analytics.position_cycle_fact COMMENT COLUMN trace_id '链路追踪标识';