// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: common/proto/strategy.proto

package strategy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StrategyService_StartStrategy_FullMethodName     = "/strategy.StrategyService/StartStrategy"
	StrategyService_StopStrategy_FullMethodName      = "/strategy.StrategyService/StopStrategy"
	StrategyService_GetStrategyStatus_FullMethodName = "/strategy.StrategyService/GetStrategyStatus"
	StrategyService_StreamSignals_FullMethodName     = "/strategy.StrategyService/StreamSignals"
)

// StrategyServiceClient is the client API for StrategyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyServiceClient interface {
	// 启动策略
	StartStrategy(ctx context.Context, in *StrategyConfig, opts ...grpc.CallOption) (*StrategyStatus, error)
	// 停止策略
	StopStrategy(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (*StrategyStatus, error)
	// 获取策略状态
	GetStrategyStatus(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (*StrategyStatus, error)
	// 获取策略信号流
	StreamSignals(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Signal], error)
}

type strategyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyServiceClient(cc grpc.ClientConnInterface) StrategyServiceClient {
	return &strategyServiceClient{cc}
}

func (c *strategyServiceClient) StartStrategy(ctx context.Context, in *StrategyConfig, opts ...grpc.CallOption) (*StrategyStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyStatus)
	err := c.cc.Invoke(ctx, StrategyService_StartStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) StopStrategy(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (*StrategyStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyStatus)
	err := c.cc.Invoke(ctx, StrategyService_StopStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) GetStrategyStatus(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (*StrategyStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyStatus)
	err := c.cc.Invoke(ctx, StrategyService_GetStrategyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) StreamSignals(ctx context.Context, in *StrategyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Signal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StrategyService_ServiceDesc.Streams[0], StrategyService_StreamSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StrategyRequest, Signal]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StrategyService_StreamSignalsClient = grpc.ServerStreamingClient[Signal]

// StrategyServiceServer is the server API for StrategyService service.
// All implementations must embed UnimplementedStrategyServiceServer
// for forward compatibility.
type StrategyServiceServer interface {
	// 启动策略
	StartStrategy(context.Context, *StrategyConfig) (*StrategyStatus, error)
	// 停止策略
	StopStrategy(context.Context, *StrategyRequest) (*StrategyStatus, error)
	// 获取策略状态
	GetStrategyStatus(context.Context, *StrategyRequest) (*StrategyStatus, error)
	// 获取策略信号流
	StreamSignals(*StrategyRequest, grpc.ServerStreamingServer[Signal]) error
	mustEmbedUnimplementedStrategyServiceServer()
}

// UnimplementedStrategyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyServiceServer struct{}

func (UnimplementedStrategyServiceServer) StartStrategy(context.Context, *StrategyConfig) (*StrategyStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StartStrategy not implemented")
}
func (UnimplementedStrategyServiceServer) StopStrategy(context.Context, *StrategyRequest) (*StrategyStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StopStrategy not implemented")
}
func (UnimplementedStrategyServiceServer) GetStrategyStatus(context.Context, *StrategyRequest) (*StrategyStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStrategyStatus not implemented")
}
func (UnimplementedStrategyServiceServer) StreamSignals(*StrategyRequest, grpc.ServerStreamingServer[Signal]) error {
	return status.Error(codes.Unimplemented, "method StreamSignals not implemented")
}
func (UnimplementedStrategyServiceServer) mustEmbedUnimplementedStrategyServiceServer() {}
func (UnimplementedStrategyServiceServer) testEmbeddedByValue()                         {}

// UnsafeStrategyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyServiceServer will
// result in compilation errors.
type UnsafeStrategyServiceServer interface {
	mustEmbedUnimplementedStrategyServiceServer()
}

func RegisterStrategyServiceServer(s grpc.ServiceRegistrar, srv StrategyServiceServer) {
	// If the following call panics, it indicates UnimplementedStrategyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StrategyService_ServiceDesc, srv)
}

func _StrategyService_StartStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).StartStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_StartStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).StartStrategy(ctx, req.(*StrategyConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_StopStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).StopStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_StopStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).StopStrategy(ctx, req.(*StrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_GetStrategyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).GetStrategyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_GetStrategyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).GetStrategyStatus(ctx, req.(*StrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_StreamSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StrategyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StrategyServiceServer).StreamSignals(m, &grpc.GenericServerStream[StrategyRequest, Signal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StrategyService_StreamSignalsServer = grpc.ServerStreamingServer[Signal]

// StrategyService_ServiceDesc is the grpc.ServiceDesc for StrategyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StrategyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "strategy.StrategyService",
	HandlerType: (*StrategyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartStrategy",
			Handler:    _StrategyService_StartStrategy_Handler,
		},
		{
			MethodName: "StopStrategy",
			Handler:    _StrategyService_StopStrategy_Handler,
		},
		{
			MethodName: "GetStrategyStatus",
			Handler:    _StrategyService_GetStrategyStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSignals",
			Handler:       _StrategyService_StreamSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "common/proto/strategy.proto",
}
