// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: strategy.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 交易信号
type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // BUY, SELL, HOLD
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`     // LONG, SHORT
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EntryPrice    float64                `protobuf:"fixed64,6,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	StopLoss      float64                `protobuf:"fixed64,7,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	TakeProfits   []float64              `protobuf:"fixed64,8,rep,packed,name=take_profits,json=takeProfits,proto3" json:"take_profits,omitempty"`
	Reason        string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *Signal) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *Signal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Signal) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Signal) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Signal) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Signal) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *Signal) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *Signal) GetTakeProfits() []float64 {
	if x != nil {
		return x.TakeProfits
	}
	return nil
}

func (x *Signal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Signal) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 策略配置
type StrategyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Parameters    map[string]float64     `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyConfig) Reset() {
	*x = StrategyConfig{}
	mi := &file_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyConfig) ProtoMessage() {}

func (x *StrategyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyConfig.ProtoReflect.Descriptor instead.
func (*StrategyConfig) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *StrategyConfig) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StrategyConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StrategyConfig) GetParameters() map[string]float64 {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *StrategyConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 策略状态
type StrategyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // RUNNING, STOPPED, ERROR
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LastUpdate    int64                  `protobuf:"varint,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyStatus) Reset() {
	*x = StrategyStatus{}
	mi := &file_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyStatus) ProtoMessage() {}

func (x *StrategyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyStatus.ProtoReflect.Descriptor instead.
func (*StrategyStatus) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *StrategyStatus) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *StrategyStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StrategyStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StrategyStatus) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

type StrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyRequest) Reset() {
	*x = StrategyRequest{}
	mi := &file_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyRequest) ProtoMessage() {}

func (x *StrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyRequest.ProtoReflect.Descriptor instead.
func (*StrategyRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *StrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

var File_strategy_proto protoreflect.FileDescriptor

const file_strategy_proto_rawDesc = "" +
	"\n" +
	"\x0estrategy.proto\x12\bstrategy\"\xa0\x02\n" +
	"\x06Signal\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x1f\n" +
	"\ventry_price\x18\x06 \x01(\x01R\n" +
	"entryPrice\x12\x1b\n" +
	"\tstop_loss\x18\a \x01(\x01R\bstopLoss\x12!\n" +
	"\ftake_profits\x18\b \x03(\x01R\vtakeProfits\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\"\xdf\x01\n" +
	"\x0eStrategyConfig\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12H\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2(.strategy.StrategyConfig.ParametersEntryR\n" +
	"parameters\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x84\x01\n" +
	"\x0eStrategyStatus\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vlast_update\x18\x04 \x01(\x03R\n" +
	"lastUpdate\"2\n" +
	"\x0fStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId2\xad\x02\n" +
	"\x0fStrategyService\x12E\n" +
	"\rStartStrategy\x12\x18.strategy.StrategyConfig\x1a\x18.strategy.StrategyStatus\"\x00\x12E\n" +
	"\fStopStrategy\x12\x19.strategy.StrategyRequest\x1a\x18.strategy.StrategyStatus\"\x00\x12J\n" +
	"\x11GetStrategyStatus\x12\x19.strategy.StrategyRequest\x1a\x18.strategy.StrategyStatus\"\x00\x12@\n" +
	"\rStreamSignals\x12\x19.strategy.StrategyRequest\x1a\x10.strategy.Signal\"\x000\x01B\fZ\n" +
	"./strategyb\x06proto3"

var (
	file_strategy_proto_rawDescOnce sync.Once
	file_strategy_proto_rawDescData []byte
)

func file_strategy_proto_rawDescGZIP() []byte {
	file_strategy_proto_rawDescOnce.Do(func() {
		file_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)))
	})
	return file_strategy_proto_rawDescData
}

var file_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_strategy_proto_goTypes = []any{
	(*Signal)(nil),          // 0: strategy.Signal
	(*StrategyConfig)(nil),  // 1: strategy.StrategyConfig
	(*StrategyStatus)(nil),  // 2: strategy.StrategyStatus
	(*StrategyRequest)(nil), // 3: strategy.StrategyRequest
	nil,                     // 4: strategy.StrategyConfig.ParametersEntry
}
var file_strategy_proto_depIdxs = []int32{
	4, // 0: strategy.StrategyConfig.parameters:type_name -> strategy.StrategyConfig.ParametersEntry
	1, // 1: strategy.StrategyService.StartStrategy:input_type -> strategy.StrategyConfig
	3, // 2: strategy.StrategyService.StopStrategy:input_type -> strategy.StrategyRequest
	3, // 3: strategy.StrategyService.GetStrategyStatus:input_type -> strategy.StrategyRequest
	3, // 4: strategy.StrategyService.StreamSignals:input_type -> strategy.StrategyRequest
	2, // 5: strategy.StrategyService.StartStrategy:output_type -> strategy.StrategyStatus
	2, // 6: strategy.StrategyService.StopStrategy:output_type -> strategy.StrategyStatus
	2, // 7: strategy.StrategyService.GetStrategyStatus:output_type -> strategy.StrategyStatus
	0, // 8: strategy.StrategyService.StreamSignals:output_type -> strategy.Signal
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_strategy_proto_init() }
func file_strategy_proto_init() {
	if File_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_proto_goTypes,
		DependencyIndexes: file_strategy_proto_depIdxs,
		MessageInfos:      file_strategy_proto_msgTypes,
	}.Build()
	File_strategy_proto = out.File
	file_strategy_proto_goTypes = nil
	file_strategy_proto_depIdxs = nil
}
