// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: strategy.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 交易信号 — execution 只消费此消息，不消费原始K线
//
// 数据流：Market(Kline) → Strategy(分析+决策) → Signal → Execution(下单+风控)
//
// Signal 包含"可执行"信息：方向、数量、止损止盈、信号类型
// 不包含：原始K线数据、中间指标计算过程
type SignalReason struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Summary          string                   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`                                           // 兼容旧链路的摘要描述
	Phase            string                   `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`                                               // OPEN_ENTRY / CLOSE_EXIT
	TrendContext     string                   `protobuf:"bytes,3,opt,name=trend_context,json=trendContext,proto3" json:"trend_context,omitempty"`             // 大级别趋势背景
	SetupContext     string                   `protobuf:"bytes,4,opt,name=setup_context,json=setupContext,proto3" json:"setup_context,omitempty"`             // 入场/出场触发背景
	PathContext      string                   `protobuf:"bytes,5,opt,name=path_context,json=pathContext,proto3" json:"path_context,omitempty"`                // 收割路径或盘口路径背景
	ExecutionContext string                   `protobuf:"bytes,6,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"` // 止损止盈、仓位、确认条件等执行信息
	Tags             []string                 `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                                                 // 标签，如 ["15m", "trend_following", "long"]
	RouteBucket      string                   `protobuf:"bytes,8,opt,name=route_bucket,json=routeBucket,proto3" json:"route_bucket,omitempty"`                // 上游路由器产出的统一策略桶
	RouteReason      string                   `protobuf:"bytes,9,opt,name=route_reason,json=routeReason,proto3" json:"route_reason,omitempty"`                // 上游路由器产出的统一路由原因
	RouteTemplate    string                   `protobuf:"bytes,10,opt,name=route_template,json=routeTemplate,proto3" json:"route_template,omitempty"`         // 上游路由器最终选中的模板
	Allocator        *PositionAllocatorStatus `protobuf:"bytes,11,opt,name=allocator,proto3" json:"allocator,omitempty"`                                      // 发出信号时对应的 allocator 快照
	Range            *RangeSignalReason       `protobuf:"bytes,12,opt,name=range,proto3" json:"range,omitempty"`                                              // 震荡策略的结构化判定摘要，便于前端直接展示
	ExitReasonKind   string                   `protobuf:"bytes,13,opt,name=exit_reason_kind,json=exitReasonKind,proto3" json:"exit_reason_kind,omitempty"`    // 结构化出场原因分类，如 partial_take_profit / break_even_stop / rsi_take_profit
	ExitReasonLabel  string                   `protobuf:"bytes,14,opt,name=exit_reason_label,json=exitReasonLabel,proto3" json:"exit_reason_label,omitempty"` // 出场原因中文标签，如 分批止盈 / 保本止损 / RSI止盈
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignalReason) Reset() {
	*x = SignalReason{}
	mi := &file_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalReason) ProtoMessage() {}

func (x *SignalReason) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalReason.ProtoReflect.Descriptor instead.
func (*SignalReason) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *SignalReason) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SignalReason) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SignalReason) GetTrendContext() string {
	if x != nil {
		return x.TrendContext
	}
	return ""
}

func (x *SignalReason) GetSetupContext() string {
	if x != nil {
		return x.SetupContext
	}
	return ""
}

func (x *SignalReason) GetPathContext() string {
	if x != nil {
		return x.PathContext
	}
	return ""
}

func (x *SignalReason) GetExecutionContext() string {
	if x != nil {
		return x.ExecutionContext
	}
	return ""
}

func (x *SignalReason) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SignalReason) GetRouteBucket() string {
	if x != nil {
		return x.RouteBucket
	}
	return ""
}

func (x *SignalReason) GetRouteReason() string {
	if x != nil {
		return x.RouteReason
	}
	return ""
}

func (x *SignalReason) GetRouteTemplate() string {
	if x != nil {
		return x.RouteTemplate
	}
	return ""
}

func (x *SignalReason) GetAllocator() *PositionAllocatorStatus {
	if x != nil {
		return x.Allocator
	}
	return nil
}

func (x *SignalReason) GetRange() *RangeSignalReason {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *SignalReason) GetExitReasonKind() string {
	if x != nil {
		return x.ExitReasonKind
	}
	return ""
}

func (x *SignalReason) GetExitReasonLabel() string {
	if x != nil {
		return x.ExitReasonLabel
	}
	return ""
}

type RangeSignalReason struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	H1RangeOk      bool                   `protobuf:"varint,1,opt,name=h1_range_ok,json=h1RangeOk,proto3" json:"h1_range_ok,omitempty"`                  // 1H 是否满足震荡前提
	H1AdxOk        bool                   `protobuf:"varint,2,opt,name=h1_adx_ok,json=h1AdxOk,proto3" json:"h1_adx_ok,omitempty"`                        // 1H ADX 是否低于阈值
	H1BollWidthOk  bool                   `protobuf:"varint,3,opt,name=h1_boll_width_ok,json=h1BollWidthOk,proto3" json:"h1_boll_width_ok,omitempty"`    // 1H Boll 带宽是否足够收窄
	M15TouchLower  bool                   `protobuf:"varint,4,opt,name=m15_touch_lower,json=m15TouchLower,proto3" json:"m15_touch_lower,omitempty"`      // 15M 是否触及下轨
	M15RsiTurnUp   bool                   `protobuf:"varint,5,opt,name=m15_rsi_turn_up,json=m15RsiTurnUp,proto3" json:"m15_rsi_turn_up,omitempty"`       // 15M RSI 是否拐头向上
	M15TouchUpper  bool                   `protobuf:"varint,6,opt,name=m15_touch_upper,json=m15TouchUpper,proto3" json:"m15_touch_upper,omitempty"`      // 15M 是否触及上轨
	M15RsiTurnDown bool                   `protobuf:"varint,7,opt,name=m15_rsi_turn_down,json=m15RsiTurnDown,proto3" json:"m15_rsi_turn_down,omitempty"` // 15M RSI 是否拐头向下
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RangeSignalReason) Reset() {
	*x = RangeSignalReason{}
	mi := &file_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSignalReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSignalReason) ProtoMessage() {}

func (x *RangeSignalReason) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSignalReason.ProtoReflect.Descriptor instead.
func (*RangeSignalReason) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *RangeSignalReason) GetH1RangeOk() bool {
	if x != nil {
		return x.H1RangeOk
	}
	return false
}

func (x *RangeSignalReason) GetH1AdxOk() bool {
	if x != nil {
		return x.H1AdxOk
	}
	return false
}

func (x *RangeSignalReason) GetH1BollWidthOk() bool {
	if x != nil {
		return x.H1BollWidthOk
	}
	return false
}

func (x *RangeSignalReason) GetM15TouchLower() bool {
	if x != nil {
		return x.M15TouchLower
	}
	return false
}

func (x *RangeSignalReason) GetM15RsiTurnUp() bool {
	if x != nil {
		return x.M15RsiTurnUp
	}
	return false
}

func (x *RangeSignalReason) GetM15TouchUpper() bool {
	if x != nil {
		return x.M15TouchUpper
	}
	return false
}

func (x *RangeSignalReason) GetM15RsiTurnDown() bool {
	if x != nil {
		return x.M15RsiTurnDown
	}
	return false
}

type Signal struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	StrategyId  string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`             // 策略ID，如 "trend-following-BTCUSDT"
	Symbol      string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                       // 交易对，如 "BTCUSDT"
	Action      string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                       // 动作：BUY, SELL, HOLD
	Side        string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`                                           // 仓位方向：LONG, SHORT
	Quantity    float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`                                 // 下单数量
	EntryPrice  float64                `protobuf:"fixed64,6,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`           // 入场/出场价格
	StopLoss    float64                `protobuf:"fixed64,7,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`                 // 止损价
	TakeProfits []float64              `protobuf:"fixed64,8,rep,packed,name=take_profits,json=takeProfits,proto3" json:"take_profits,omitempty"` // 止盈价列表
	Reason      string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`                                       // 兼容旧链路的摘要原因
	Timestamp   int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                               // 信号时间戳（毫秒）
	SignalType  string                 `protobuf:"bytes,11,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`            // 信号类型：OPEN=开仓, CLOSE=平仓, HOLD=持仓观察
	Interval    string                 `protobuf:"bytes,12,opt,name=interval,proto3" json:"interval,omitempty"`                                  // 信号周期，如 "15m"
	Atr         float64                `protobuf:"fixed64,13,opt,name=atr,proto3" json:"atr,omitempty"`                                          // 当前ATR（execution用于计算滑点容忍度）
	RiskReward  float64                `protobuf:"fixed64,14,opt,name=risk_reward,json=riskReward,proto3" json:"risk_reward,omitempty"`          // 风险收益比（如 2.0 表示盈亏比 1:2）
	// 指标快照 — 供日志/审计用，execution 不做计算
	Indicators    map[string]float64 `protobuf:"bytes,15,rep,name=indicators,proto3" json:"indicators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // 如 {"h4_ema21":68000, "m15_rsi":62.3, "m15_atr":350}
	SignalReason  *SignalReason      `protobuf:"bytes,16,opt,name=signal_reason,json=signalReason,proto3" json:"signal_reason,omitempty"`                                                     // 结构化原因描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *Signal) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *Signal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Signal) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Signal) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Signal) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Signal) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *Signal) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *Signal) GetTakeProfits() []float64 {
	if x != nil {
		return x.TakeProfits
	}
	return nil
}

func (x *Signal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Signal) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Signal) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *Signal) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *Signal) GetAtr() float64 {
	if x != nil {
		return x.Atr
	}
	return 0
}

func (x *Signal) GetRiskReward() float64 {
	if x != nil {
		return x.RiskReward
	}
	return 0
}

func (x *Signal) GetIndicators() map[string]float64 {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *Signal) GetSignalReason() *SignalReason {
	if x != nil {
		return x.SignalReason
	}
	return nil
}

// 策略配置
type StrategyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Parameters    map[string]float64     `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyConfig) Reset() {
	*x = StrategyConfig{}
	mi := &file_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyConfig) ProtoMessage() {}

func (x *StrategyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyConfig.ProtoReflect.Descriptor instead.
func (*StrategyConfig) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *StrategyConfig) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StrategyConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StrategyConfig) GetParameters() map[string]float64 {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *StrategyConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 策略状态
type PositionAllocatorStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Template        string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`                                         // 当前 symbol 最终使用的策略模板
	RouteBucket     string                 `protobuf:"bytes,2,opt,name=route_bucket,json=routeBucket,proto3" json:"route_bucket,omitempty"`                // 当前 symbol 对应的统一策略桶
	RouteReason     string                 `protobuf:"bytes,3,opt,name=route_reason,json=routeReason,proto3" json:"route_reason,omitempty"`                // 当前 symbol 对应的统一路由原因
	Score           float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`                                             // 当前 symbol 预算分配使用的最终 score
	ScoreSource     string                 `protobuf:"bytes,5,opt,name=score_source,json=scoreSource,proto3" json:"score_source,omitempty"`                // score 的来源，如 symbol_score / regime_analysis
	BucketBudget    float64                `protobuf:"fixed64,6,opt,name=bucket_budget,json=bucketBudget,proto3" json:"bucket_budget,omitempty"`           // 当前策略桶的总预算
	StrategyWeight  float64                `protobuf:"fixed64,7,opt,name=strategy_weight,json=strategyWeight,proto3" json:"strategy_weight,omitempty"`     // 当前策略桶在本轮 allocator 中的配比
	SymbolWeight    float64                `protobuf:"fixed64,8,opt,name=symbol_weight,json=symbolWeight,proto3" json:"symbol_weight,omitempty"`           // 当前 symbol 在桶内的配比
	RiskScale       float64                `protobuf:"fixed64,9,opt,name=risk_scale,json=riskScale,proto3" json:"risk_scale,omitempty"`                    // 当前全局风险缩放系数
	PositionBudget  float64                `protobuf:"fixed64,10,opt,name=position_budget,json=positionBudget,proto3" json:"position_budget,omitempty"`    // 当前 symbol 的最终仓位预算
	TradingPaused   bool                   `protobuf:"varint,11,opt,name=trading_paused,json=tradingPaused,proto3" json:"trading_paused,omitempty"`        // 当前轮是否被 allocator 暂停交易
	PauseReason     string                 `protobuf:"bytes,12,opt,name=pause_reason,json=pauseReason,proto3" json:"pause_reason,omitempty"`               // allocator 暂停原因
	RouteReasonDesc string                 `protobuf:"bytes,13,opt,name=route_reason_desc,json=routeReasonDesc,proto3" json:"route_reason_desc,omitempty"` // route_reason 的中文说明，供前端直接展示
	PauseReasonDesc string                 `protobuf:"bytes,14,opt,name=pause_reason_desc,json=pauseReasonDesc,proto3" json:"pause_reason_desc,omitempty"` // pause_reason 的中文说明，供前端直接展示
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PositionAllocatorStatus) Reset() {
	*x = PositionAllocatorStatus{}
	mi := &file_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionAllocatorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionAllocatorStatus) ProtoMessage() {}

func (x *PositionAllocatorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionAllocatorStatus.ProtoReflect.Descriptor instead.
func (*PositionAllocatorStatus) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *PositionAllocatorStatus) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *PositionAllocatorStatus) GetRouteBucket() string {
	if x != nil {
		return x.RouteBucket
	}
	return ""
}

func (x *PositionAllocatorStatus) GetRouteReason() string {
	if x != nil {
		return x.RouteReason
	}
	return ""
}

func (x *PositionAllocatorStatus) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PositionAllocatorStatus) GetScoreSource() string {
	if x != nil {
		return x.ScoreSource
	}
	return ""
}

func (x *PositionAllocatorStatus) GetBucketBudget() float64 {
	if x != nil {
		return x.BucketBudget
	}
	return 0
}

func (x *PositionAllocatorStatus) GetStrategyWeight() float64 {
	if x != nil {
		return x.StrategyWeight
	}
	return 0
}

func (x *PositionAllocatorStatus) GetSymbolWeight() float64 {
	if x != nil {
		return x.SymbolWeight
	}
	return 0
}

func (x *PositionAllocatorStatus) GetRiskScale() float64 {
	if x != nil {
		return x.RiskScale
	}
	return 0
}

func (x *PositionAllocatorStatus) GetPositionBudget() float64 {
	if x != nil {
		return x.PositionBudget
	}
	return 0
}

func (x *PositionAllocatorStatus) GetTradingPaused() bool {
	if x != nil {
		return x.TradingPaused
	}
	return false
}

func (x *PositionAllocatorStatus) GetPauseReason() string {
	if x != nil {
		return x.PauseReason
	}
	return ""
}

func (x *PositionAllocatorStatus) GetRouteReasonDesc() string {
	if x != nil {
		return x.RouteReasonDesc
	}
	return ""
}

func (x *PositionAllocatorStatus) GetPauseReasonDesc() string {
	if x != nil {
		return x.PauseReasonDesc
	}
	return ""
}

type RegimeFrameStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Interval        string                 `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`                                         // 周期，如 1h / 15m
	State           string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                                               // 该周期当前识别出的状态
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                             // 该周期 marketstate 原始原因
	RouteReason     string                 `protobuf:"bytes,4,opt,name=route_reason,json=routeReason,proto3" json:"route_reason,omitempty"`                // 该周期映射后的统一路由原因
	Confidence      float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`                                   // 该周期判态置信度
	LastUpdate      int64                  `protobuf:"varint,6,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`                  // 该周期最近一次更新时间
	Healthy         bool                   `protobuf:"varint,7,opt,name=healthy,proto3" json:"healthy,omitempty"`                                          // 该周期特征是否健康
	Fresh           bool                   `protobuf:"varint,8,opt,name=fresh,proto3" json:"fresh,omitempty"`                                              // 该周期特征是否在 freshness window 内
	ReasonDesc      string                 `protobuf:"bytes,9,opt,name=reason_desc,json=reasonDesc,proto3" json:"reason_desc,omitempty"`                   // reason 的中文说明，供前端直接展示
	RouteReasonDesc string                 `protobuf:"bytes,10,opt,name=route_reason_desc,json=routeReasonDesc,proto3" json:"route_reason_desc,omitempty"` // route_reason 的中文说明，供前端直接展示
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegimeFrameStatus) Reset() {
	*x = RegimeFrameStatus{}
	mi := &file_strategy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegimeFrameStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegimeFrameStatus) ProtoMessage() {}

func (x *RegimeFrameStatus) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegimeFrameStatus.ProtoReflect.Descriptor instead.
func (*RegimeFrameStatus) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *RegimeFrameStatus) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *RegimeFrameStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RegimeFrameStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegimeFrameStatus) GetRouteReason() string {
	if x != nil {
		return x.RouteReason
	}
	return ""
}

func (x *RegimeFrameStatus) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RegimeFrameStatus) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *RegimeFrameStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *RegimeFrameStatus) GetFresh() bool {
	if x != nil {
		return x.Fresh
	}
	return false
}

func (x *RegimeFrameStatus) GetReasonDesc() string {
	if x != nil {
		return x.ReasonDesc
	}
	return ""
}

func (x *RegimeFrameStatus) GetRouteReasonDesc() string {
	if x != nil {
		return x.RouteReasonDesc
	}
	return ""
}

type RegimeFusionStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	H1              *RegimeFrameStatus     `protobuf:"bytes,1,opt,name=h1,proto3" json:"h1,omitempty"`                                                    // 1H 主状态
	M15             *RegimeFrameStatus     `protobuf:"bytes,2,opt,name=m15,proto3" json:"m15,omitempty"`                                                  // 15M 辅助状态
	FusedState      string                 `protobuf:"bytes,3,opt,name=fused_state,json=fusedState,proto3" json:"fused_state,omitempty"`                  // 加权融合后的最终状态
	FusedReason     string                 `protobuf:"bytes,4,opt,name=fused_reason,json=fusedReason,proto3" json:"fused_reason,omitempty"`               // 融合原因，如 timeframes_aligned / h1_primary_dominant
	FusedScore      float64                `protobuf:"fixed64,5,opt,name=fused_score,json=fusedScore,proto3" json:"fused_score,omitempty"`                // 融合得分
	PrimaryWeight   float64                `protobuf:"fixed64,6,opt,name=primary_weight,json=primaryWeight,proto3" json:"primary_weight,omitempty"`       // 主状态权重，当前默认 0.7
	ConfirmWeight   float64                `protobuf:"fixed64,7,opt,name=confirm_weight,json=confirmWeight,proto3" json:"confirm_weight,omitempty"`       // 辅助状态权重，当前默认 0.3
	LastUpdate      int64                  `protobuf:"varint,8,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`                 // 融合结果更新时间
	FusedReasonDesc string                 `protobuf:"bytes,9,opt,name=fused_reason_desc,json=fusedReasonDesc,proto3" json:"fused_reason_desc,omitempty"` // fused_reason 的中文说明，供前端直接展示
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegimeFusionStatus) Reset() {
	*x = RegimeFusionStatus{}
	mi := &file_strategy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegimeFusionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegimeFusionStatus) ProtoMessage() {}

func (x *RegimeFusionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegimeFusionStatus.ProtoReflect.Descriptor instead.
func (*RegimeFusionStatus) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *RegimeFusionStatus) GetH1() *RegimeFrameStatus {
	if x != nil {
		return x.H1
	}
	return nil
}

func (x *RegimeFusionStatus) GetM15() *RegimeFrameStatus {
	if x != nil {
		return x.M15
	}
	return nil
}

func (x *RegimeFusionStatus) GetFusedState() string {
	if x != nil {
		return x.FusedState
	}
	return ""
}

func (x *RegimeFusionStatus) GetFusedReason() string {
	if x != nil {
		return x.FusedReason
	}
	return ""
}

func (x *RegimeFusionStatus) GetFusedScore() float64 {
	if x != nil {
		return x.FusedScore
	}
	return 0
}

func (x *RegimeFusionStatus) GetPrimaryWeight() float64 {
	if x != nil {
		return x.PrimaryWeight
	}
	return 0
}

func (x *RegimeFusionStatus) GetConfirmWeight() float64 {
	if x != nil {
		return x.ConfirmWeight
	}
	return 0
}

func (x *RegimeFusionStatus) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *RegimeFusionStatus) GetFusedReasonDesc() string {
	if x != nil {
		return x.FusedReasonDesc
	}
	return ""
}

type StrategyWarmupStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HistoryLen_4H     int32                  `protobuf:"varint,1,opt,name=history_len_4h,json=historyLen4h,proto3" json:"history_len_4h,omitempty"`             // 当前 4H 历史缓存长度
	HistoryLen_1H     int32                  `protobuf:"varint,2,opt,name=history_len_1h,json=historyLen1h,proto3" json:"history_len_1h,omitempty"`             // 当前 1H 历史缓存长度
	HistoryLen_15M    int32                  `protobuf:"varint,3,opt,name=history_len_15m,json=historyLen15m,proto3" json:"history_len_15m,omitempty"`          // 当前 15M 历史缓存长度
	HistoryLen_1M     int32                  `protobuf:"varint,4,opt,name=history_len_1m,json=historyLen1m,proto3" json:"history_len_1m,omitempty"`             // 当前 1M 历史缓存长度
	Source            string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`                                                // 长度来源：runtime / cache / empty
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                                // warmup_complete / warmup_incomplete，直接表示当前恢复是否完整
	IncompleteReasons []string               `protobuf:"bytes,7,rep,name=incomplete_reasons,json=incompleteReasons,proto3" json:"incomplete_reasons,omitempty"` // 当恢复不完整时列出缺项，如 insufficient_1h_history
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StrategyWarmupStatus) Reset() {
	*x = StrategyWarmupStatus{}
	mi := &file_strategy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyWarmupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyWarmupStatus) ProtoMessage() {}

func (x *StrategyWarmupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyWarmupStatus.ProtoReflect.Descriptor instead.
func (*StrategyWarmupStatus) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{7}
}

func (x *StrategyWarmupStatus) GetHistoryLen_4H() int32 {
	if x != nil {
		return x.HistoryLen_4H
	}
	return 0
}

func (x *StrategyWarmupStatus) GetHistoryLen_1H() int32 {
	if x != nil {
		return x.HistoryLen_1H
	}
	return 0
}

func (x *StrategyWarmupStatus) GetHistoryLen_15M() int32 {
	if x != nil {
		return x.HistoryLen_15M
	}
	return 0
}

func (x *StrategyWarmupStatus) GetHistoryLen_1M() int32 {
	if x != nil {
		return x.HistoryLen_1M
	}
	return 0
}

func (x *StrategyWarmupStatus) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StrategyWarmupStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StrategyWarmupStatus) GetIncompleteReasons() []string {
	if x != nil {
		return x.IncompleteReasons
	}
	return nil
}

type LatestSecondBarStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenTimeMs    int64                  `protobuf:"varint,1,opt,name=open_time_ms,json=openTimeMs,proto3" json:"open_time_ms,omitempty"`    // 最近一条秒级行情的起始毫秒时间
	CloseTimeMs   int64                  `protobuf:"varint,2,opt,name=close_time_ms,json=closeTimeMs,proto3" json:"close_time_ms,omitempty"` // 最近一条秒级行情的结束毫秒时间
	Open          float64                `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`                                   // 最近一条秒级行情开盘价
	High          float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`                                   // 最近一条秒级行情最高价
	Low           float64                `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`                                     // 最近一条秒级行情最低价
	Close         float64                `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`                                 // 最近一条秒级行情收盘价
	Volume        float64                `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`                               // 最近一条秒级行情累计成交量
	IsFinal       bool                   `protobuf:"varint,8,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`               // 最近一条秒级行情是否已封口
	Synthetic     bool                   `protobuf:"varint,9,opt,name=synthetic,proto3" json:"synthetic,omitempty"`                          // 是否来自盘口兜底而非真实成交
	Source        string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`                                // trade / depth_fallback
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatestSecondBarStatus) Reset() {
	*x = LatestSecondBarStatus{}
	mi := &file_strategy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestSecondBarStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestSecondBarStatus) ProtoMessage() {}

func (x *LatestSecondBarStatus) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestSecondBarStatus.ProtoReflect.Descriptor instead.
func (*LatestSecondBarStatus) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{8}
}

func (x *LatestSecondBarStatus) GetOpenTimeMs() int64 {
	if x != nil {
		return x.OpenTimeMs
	}
	return 0
}

func (x *LatestSecondBarStatus) GetCloseTimeMs() int64 {
	if x != nil {
		return x.CloseTimeMs
	}
	return 0
}

func (x *LatestSecondBarStatus) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *LatestSecondBarStatus) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *LatestSecondBarStatus) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *LatestSecondBarStatus) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *LatestSecondBarStatus) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *LatestSecondBarStatus) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *LatestSecondBarStatus) GetSynthetic() bool {
	if x != nil {
		return x.Synthetic
	}
	return false
}

func (x *LatestSecondBarStatus) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type StrategyRouteRuntimeStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Enabled             bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                        // Universe 当前轮目标是否允许启用该策略
	Template            string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`                                                       // Universe 当前轮目标模板
	RouteBucket         string                 `protobuf:"bytes,3,opt,name=route_bucket,json=routeBucket,proto3" json:"route_bucket,omitempty"`                              // Universe 当前轮目标策略桶
	TargetReason        string                 `protobuf:"bytes,4,opt,name=target_reason,json=targetReason,proto3" json:"target_reason,omitempty"`                           // Universe 当前轮目标原因，可能来自路由、健康门禁或保护规则
	BaseTemplate        string                 `protobuf:"bytes,5,opt,name=base_template,json=baseTemplate,proto3" json:"base_template,omitempty"`                           // Universe 当前轮路由前的基础模板
	RuntimeEnabled      bool                   `protobuf:"varint,6,opt,name=runtime_enabled,json=runtimeEnabled,proto3" json:"runtime_enabled,omitempty"`                    // Universe 应用后当前实际是否保持启用
	RuntimeTemplate     string                 `protobuf:"bytes,7,opt,name=runtime_template,json=runtimeTemplate,proto3" json:"runtime_template,omitempty"`                  // Universe 应用后当前实际模板
	ApplyAction         string                 `protobuf:"bytes,8,opt,name=apply_action,json=applyAction,proto3" json:"apply_action,omitempty"`                              // 当前轮 Universe 对该 symbol 执行的动作
	ApplyGateReason     string                 `protobuf:"bytes,9,opt,name=apply_gate_reason,json=applyGateReason,proto3" json:"apply_gate_reason,omitempty"`                // 当前实际状态与目标态不一致时的运行时门禁原因
	HasStrategy         bool                   `protobuf:"varint,10,opt,name=has_strategy,json=hasStrategy,proto3" json:"has_strategy,omitempty"`                            // 当前运行时是否存在策略实例
	HasOpenPosition     bool                   `protobuf:"varint,11,opt,name=has_open_position,json=hasOpenPosition,proto3" json:"has_open_position,omitempty"`              // 当前是否仍持有未平仓位
	RegimeFusion        *RegimeFusionStatus    `protobuf:"bytes,12,opt,name=regime_fusion,json=regimeFusion,proto3" json:"regime_fusion,omitempty"`                          // Universe 最近一轮 1H/15M 多周期融合判态
	Warmup              *StrategyWarmupStatus  `protobuf:"bytes,13,opt,name=warmup,proto3" json:"warmup,omitempty"`                                                          // 当前实例或缓存中的多周期历史长度，便于判断冷启动恢复是否完整
	TargetReasonDesc    string                 `protobuf:"bytes,14,opt,name=target_reason_desc,json=targetReasonDesc,proto3" json:"target_reason_desc,omitempty"`            // target_reason 的中文说明，供前端直接展示
	ApplyGateReasonDesc string                 `protobuf:"bytes,15,opt,name=apply_gate_reason_desc,json=applyGateReasonDesc,proto3" json:"apply_gate_reason_desc,omitempty"` // apply_gate_reason 的中文说明，供前端直接展示
	ApplyActionDesc     string                 `protobuf:"bytes,16,opt,name=apply_action_desc,json=applyActionDesc,proto3" json:"apply_action_desc,omitempty"`               // apply_action 的中文说明，供前端直接展示
	LatestSecondBar     *LatestSecondBarStatus `protobuf:"bytes,17,opt,name=latest_second_bar,json=latestSecondBar,proto3" json:"latest_second_bar,omitempty"`               // 最近一条 1s 输入行情，便于确认 synthetic fallback 是否生效
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StrategyRouteRuntimeStatus) Reset() {
	*x = StrategyRouteRuntimeStatus{}
	mi := &file_strategy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyRouteRuntimeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyRouteRuntimeStatus) ProtoMessage() {}

func (x *StrategyRouteRuntimeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyRouteRuntimeStatus.ProtoReflect.Descriptor instead.
func (*StrategyRouteRuntimeStatus) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{9}
}

func (x *StrategyRouteRuntimeStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StrategyRouteRuntimeStatus) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetRouteBucket() string {
	if x != nil {
		return x.RouteBucket
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetTargetReason() string {
	if x != nil {
		return x.TargetReason
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetBaseTemplate() string {
	if x != nil {
		return x.BaseTemplate
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetRuntimeEnabled() bool {
	if x != nil {
		return x.RuntimeEnabled
	}
	return false
}

func (x *StrategyRouteRuntimeStatus) GetRuntimeTemplate() string {
	if x != nil {
		return x.RuntimeTemplate
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetApplyAction() string {
	if x != nil {
		return x.ApplyAction
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetApplyGateReason() string {
	if x != nil {
		return x.ApplyGateReason
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetHasStrategy() bool {
	if x != nil {
		return x.HasStrategy
	}
	return false
}

func (x *StrategyRouteRuntimeStatus) GetHasOpenPosition() bool {
	if x != nil {
		return x.HasOpenPosition
	}
	return false
}

func (x *StrategyRouteRuntimeStatus) GetRegimeFusion() *RegimeFusionStatus {
	if x != nil {
		return x.RegimeFusion
	}
	return nil
}

func (x *StrategyRouteRuntimeStatus) GetWarmup() *StrategyWarmupStatus {
	if x != nil {
		return x.Warmup
	}
	return nil
}

func (x *StrategyRouteRuntimeStatus) GetTargetReasonDesc() string {
	if x != nil {
		return x.TargetReasonDesc
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetApplyGateReasonDesc() string {
	if x != nil {
		return x.ApplyGateReasonDesc
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetApplyActionDesc() string {
	if x != nil {
		return x.ApplyActionDesc
	}
	return ""
}

func (x *StrategyRouteRuntimeStatus) GetLatestSecondBar() *LatestSecondBarStatus {
	if x != nil {
		return x.LatestSecondBar
	}
	return nil
}

type StrategyStatus struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	StrategyId    string                      `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Status        string                      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // RUNNING, STOPPED, ERROR
	Message       string                      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 人类可读短消息，避免承载需要机器解析的长串
	LastUpdate    int64                       `protobuf:"varint,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	Allocator     *PositionAllocatorStatus    `protobuf:"bytes,5,opt,name=allocator,proto3" json:"allocator,omitempty"`                        // 结构化 allocator 视角，便于外部直接消费
	Router        *StrategyRouteRuntimeStatus `protobuf:"bytes,6,opt,name=router,proto3" json:"router,omitempty"`                              // Universe 当前轮路由与运行时目标视角
	StatusDesc    string                      `protobuf:"bytes,7,opt,name=status_desc,json=statusDesc,proto3" json:"status_desc,omitempty"`    // status 的中文说明，供前端直接展示
	MessageCode   string                      `protobuf:"bytes,8,opt,name=message_code,json=messageCode,proto3" json:"message_code,omitempty"` // message 的稳定英文码，供前端直接判断
	MessageDesc   string                      `protobuf:"bytes,9,opt,name=message_desc,json=messageDesc,proto3" json:"message_desc,omitempty"` // message_code 的中文说明，供前端直接展示
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyStatus) Reset() {
	*x = StrategyStatus{}
	mi := &file_strategy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyStatus) ProtoMessage() {}

func (x *StrategyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyStatus.ProtoReflect.Descriptor instead.
func (*StrategyStatus) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{10}
}

func (x *StrategyStatus) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *StrategyStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StrategyStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StrategyStatus) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *StrategyStatus) GetAllocator() *PositionAllocatorStatus {
	if x != nil {
		return x.Allocator
	}
	return nil
}

func (x *StrategyStatus) GetRouter() *StrategyRouteRuntimeStatus {
	if x != nil {
		return x.Router
	}
	return nil
}

func (x *StrategyStatus) GetStatusDesc() string {
	if x != nil {
		return x.StatusDesc
	}
	return ""
}

func (x *StrategyStatus) GetMessageCode() string {
	if x != nil {
		return x.MessageCode
	}
	return ""
}

func (x *StrategyStatus) GetMessageDesc() string {
	if x != nil {
		return x.MessageDesc
	}
	return ""
}

type StrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyRequest) Reset() {
	*x = StrategyRequest{}
	mi := &file_strategy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyRequest) ProtoMessage() {}

func (x *StrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyRequest.ProtoReflect.Descriptor instead.
func (*StrategyRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{11}
}

func (x *StrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

var File_strategy_proto protoreflect.FileDescriptor

const file_strategy_proto_rawDesc = "" +
	"\n" +
	"\x0estrategy.proto\x12\bstrategy\"\xa3\x04\n" +
	"\fSignalReason\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12#\n" +
	"\rtrend_context\x18\x03 \x01(\tR\ftrendContext\x12#\n" +
	"\rsetup_context\x18\x04 \x01(\tR\fsetupContext\x12!\n" +
	"\fpath_context\x18\x05 \x01(\tR\vpathContext\x12+\n" +
	"\x11execution_context\x18\x06 \x01(\tR\x10executionContext\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12!\n" +
	"\froute_bucket\x18\b \x01(\tR\vrouteBucket\x12!\n" +
	"\froute_reason\x18\t \x01(\tR\vrouteReason\x12%\n" +
	"\x0eroute_template\x18\n" +
	" \x01(\tR\rrouteTemplate\x12?\n" +
	"\tallocator\x18\v \x01(\v2!.strategy.PositionAllocatorStatusR\tallocator\x121\n" +
	"\x05range\x18\f \x01(\v2\x1b.strategy.RangeSignalReasonR\x05range\x12(\n" +
	"\x10exit_reason_kind\x18\r \x01(\tR\x0eexitReasonKind\x12*\n" +
	"\x11exit_reason_label\x18\x0e \x01(\tR\x0fexitReasonLabel\"\x9a\x02\n" +
	"\x11RangeSignalReason\x12\x1e\n" +
	"\vh1_range_ok\x18\x01 \x01(\bR\th1RangeOk\x12\x1a\n" +
	"\th1_adx_ok\x18\x02 \x01(\bR\ah1AdxOk\x12'\n" +
	"\x10h1_boll_width_ok\x18\x03 \x01(\bR\rh1BollWidthOk\x12&\n" +
	"\x0fm15_touch_lower\x18\x04 \x01(\bR\rm15TouchLower\x12%\n" +
	"\x0fm15_rsi_turn_up\x18\x05 \x01(\bR\fm15RsiTurnUp\x12&\n" +
	"\x0fm15_touch_upper\x18\x06 \x01(\bR\rm15TouchUpper\x12)\n" +
	"\x11m15_rsi_turn_down\x18\a \x01(\bR\x0em15RsiTurnDown\"\xce\x04\n" +
	"\x06Signal\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x1f\n" +
	"\ventry_price\x18\x06 \x01(\x01R\n" +
	"entryPrice\x12\x1b\n" +
	"\tstop_loss\x18\a \x01(\x01R\bstopLoss\x12!\n" +
	"\ftake_profits\x18\b \x03(\x01R\vtakeProfits\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vsignal_type\x18\v \x01(\tR\n" +
	"signalType\x12\x1a\n" +
	"\binterval\x18\f \x01(\tR\binterval\x12\x10\n" +
	"\x03atr\x18\r \x01(\x01R\x03atr\x12\x1f\n" +
	"\vrisk_reward\x18\x0e \x01(\x01R\n" +
	"riskReward\x12@\n" +
	"\n" +
	"indicators\x18\x0f \x03(\v2 .strategy.Signal.IndicatorsEntryR\n" +
	"indicators\x12;\n" +
	"\rsignal_reason\x18\x10 \x01(\v2\x16.strategy.SignalReasonR\fsignalReason\x1a=\n" +
	"\x0fIndicatorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xdf\x01\n" +
	"\x0eStrategyConfig\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12H\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2(.strategy.StrategyConfig.ParametersEntryR\n" +
	"parameters\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x91\x04\n" +
	"\x17PositionAllocatorStatus\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12!\n" +
	"\froute_bucket\x18\x02 \x01(\tR\vrouteBucket\x12!\n" +
	"\froute_reason\x18\x03 \x01(\tR\vrouteReason\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12!\n" +
	"\fscore_source\x18\x05 \x01(\tR\vscoreSource\x12#\n" +
	"\rbucket_budget\x18\x06 \x01(\x01R\fbucketBudget\x12'\n" +
	"\x0fstrategy_weight\x18\a \x01(\x01R\x0estrategyWeight\x12#\n" +
	"\rsymbol_weight\x18\b \x01(\x01R\fsymbolWeight\x12\x1d\n" +
	"\n" +
	"risk_scale\x18\t \x01(\x01R\triskScale\x12'\n" +
	"\x0fposition_budget\x18\n" +
	" \x01(\x01R\x0epositionBudget\x12%\n" +
	"\x0etrading_paused\x18\v \x01(\bR\rtradingPaused\x12!\n" +
	"\fpause_reason\x18\f \x01(\tR\vpauseReason\x12*\n" +
	"\x11route_reason_desc\x18\r \x01(\tR\x0frouteReasonDesc\x12*\n" +
	"\x11pause_reason_desc\x18\x0e \x01(\tR\x0fpauseReasonDesc\"\xbe\x02\n" +
	"\x11RegimeFrameStatus\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\tR\binterval\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12!\n" +
	"\froute_reason\x18\x04 \x01(\tR\vrouteReason\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12\x1f\n" +
	"\vlast_update\x18\x06 \x01(\x03R\n" +
	"lastUpdate\x12\x18\n" +
	"\ahealthy\x18\a \x01(\bR\ahealthy\x12\x14\n" +
	"\x05fresh\x18\b \x01(\bR\x05fresh\x12\x1f\n" +
	"\vreason_desc\x18\t \x01(\tR\n" +
	"reasonDesc\x12*\n" +
	"\x11route_reason_desc\x18\n" +
	" \x01(\tR\x0frouteReasonDesc\"\xf0\x02\n" +
	"\x12RegimeFusionStatus\x12+\n" +
	"\x02h1\x18\x01 \x01(\v2\x1b.strategy.RegimeFrameStatusR\x02h1\x12-\n" +
	"\x03m15\x18\x02 \x01(\v2\x1b.strategy.RegimeFrameStatusR\x03m15\x12\x1f\n" +
	"\vfused_state\x18\x03 \x01(\tR\n" +
	"fusedState\x12!\n" +
	"\ffused_reason\x18\x04 \x01(\tR\vfusedReason\x12\x1f\n" +
	"\vfused_score\x18\x05 \x01(\x01R\n" +
	"fusedScore\x12%\n" +
	"\x0eprimary_weight\x18\x06 \x01(\x01R\rprimaryWeight\x12%\n" +
	"\x0econfirm_weight\x18\a \x01(\x01R\rconfirmWeight\x12\x1f\n" +
	"\vlast_update\x18\b \x01(\x03R\n" +
	"lastUpdate\x12*\n" +
	"\x11fused_reason_desc\x18\t \x01(\tR\x0ffusedReasonDesc\"\x8f\x02\n" +
	"\x14StrategyWarmupStatus\x12$\n" +
	"\x0ehistory_len_4h\x18\x01 \x01(\x05R\fhistoryLen4h\x12$\n" +
	"\x0ehistory_len_1h\x18\x02 \x01(\x05R\fhistoryLen1h\x12&\n" +
	"\x0fhistory_len_15m\x18\x03 \x01(\x05R\rhistoryLen15m\x12$\n" +
	"\x0ehistory_len_1m\x18\x04 \x01(\x05R\fhistoryLen1m\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12-\n" +
	"\x12incomplete_reasons\x18\a \x03(\tR\x11incompleteReasons\"\x96\x02\n" +
	"\x15LatestSecondBarStatus\x12 \n" +
	"\fopen_time_ms\x18\x01 \x01(\x03R\n" +
	"openTimeMs\x12\"\n" +
	"\rclose_time_ms\x18\x02 \x01(\x03R\vcloseTimeMs\x12\x12\n" +
	"\x04open\x18\x03 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\a \x01(\x01R\x06volume\x12\x19\n" +
	"\bis_final\x18\b \x01(\bR\aisFinal\x12\x1c\n" +
	"\tsynthetic\x18\t \x01(\bR\tsynthetic\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\"\x88\x06\n" +
	"\x1aStrategyRouteRuntimeStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12!\n" +
	"\froute_bucket\x18\x03 \x01(\tR\vrouteBucket\x12#\n" +
	"\rtarget_reason\x18\x04 \x01(\tR\ftargetReason\x12#\n" +
	"\rbase_template\x18\x05 \x01(\tR\fbaseTemplate\x12'\n" +
	"\x0fruntime_enabled\x18\x06 \x01(\bR\x0eruntimeEnabled\x12)\n" +
	"\x10runtime_template\x18\a \x01(\tR\x0fruntimeTemplate\x12!\n" +
	"\fapply_action\x18\b \x01(\tR\vapplyAction\x12*\n" +
	"\x11apply_gate_reason\x18\t \x01(\tR\x0fapplyGateReason\x12!\n" +
	"\fhas_strategy\x18\n" +
	" \x01(\bR\vhasStrategy\x12*\n" +
	"\x11has_open_position\x18\v \x01(\bR\x0fhasOpenPosition\x12A\n" +
	"\rregime_fusion\x18\f \x01(\v2\x1c.strategy.RegimeFusionStatusR\fregimeFusion\x126\n" +
	"\x06warmup\x18\r \x01(\v2\x1e.strategy.StrategyWarmupStatusR\x06warmup\x12,\n" +
	"\x12target_reason_desc\x18\x0e \x01(\tR\x10targetReasonDesc\x123\n" +
	"\x16apply_gate_reason_desc\x18\x0f \x01(\tR\x13applyGateReasonDesc\x12*\n" +
	"\x11apply_action_desc\x18\x10 \x01(\tR\x0fapplyActionDesc\x12K\n" +
	"\x11latest_second_bar\x18\x11 \x01(\v2\x1f.strategy.LatestSecondBarStatusR\x0flatestSecondBar\"\xea\x02\n" +
	"\x0eStrategyStatus\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vlast_update\x18\x04 \x01(\x03R\n" +
	"lastUpdate\x12?\n" +
	"\tallocator\x18\x05 \x01(\v2!.strategy.PositionAllocatorStatusR\tallocator\x12<\n" +
	"\x06router\x18\x06 \x01(\v2$.strategy.StrategyRouteRuntimeStatusR\x06router\x12\x1f\n" +
	"\vstatus_desc\x18\a \x01(\tR\n" +
	"statusDesc\x12!\n" +
	"\fmessage_code\x18\b \x01(\tR\vmessageCode\x12!\n" +
	"\fmessage_desc\x18\t \x01(\tR\vmessageDesc\"2\n" +
	"\x0fStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId2\xad\x02\n" +
	"\x0fStrategyService\x12E\n" +
	"\rStartStrategy\x12\x18.strategy.StrategyConfig\x1a\x18.strategy.StrategyStatus\"\x00\x12E\n" +
	"\fStopStrategy\x12\x19.strategy.StrategyRequest\x1a\x18.strategy.StrategyStatus\"\x00\x12J\n" +
	"\x11GetStrategyStatus\x12\x19.strategy.StrategyRequest\x1a\x18.strategy.StrategyStatus\"\x00\x12@\n" +
	"\rStreamSignals\x12\x19.strategy.StrategyRequest\x1a\x10.strategy.Signal\"\x000\x01B$Z\"exchange-system/common/pb/strategyb\x06proto3"

var (
	file_strategy_proto_rawDescOnce sync.Once
	file_strategy_proto_rawDescData []byte
)

func file_strategy_proto_rawDescGZIP() []byte {
	file_strategy_proto_rawDescOnce.Do(func() {
		file_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)))
	})
	return file_strategy_proto_rawDescData
}

var file_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_strategy_proto_goTypes = []any{
	(*SignalReason)(nil),               // 0: strategy.SignalReason
	(*RangeSignalReason)(nil),          // 1: strategy.RangeSignalReason
	(*Signal)(nil),                     // 2: strategy.Signal
	(*StrategyConfig)(nil),             // 3: strategy.StrategyConfig
	(*PositionAllocatorStatus)(nil),    // 4: strategy.PositionAllocatorStatus
	(*RegimeFrameStatus)(nil),          // 5: strategy.RegimeFrameStatus
	(*RegimeFusionStatus)(nil),         // 6: strategy.RegimeFusionStatus
	(*StrategyWarmupStatus)(nil),       // 7: strategy.StrategyWarmupStatus
	(*LatestSecondBarStatus)(nil),      // 8: strategy.LatestSecondBarStatus
	(*StrategyRouteRuntimeStatus)(nil), // 9: strategy.StrategyRouteRuntimeStatus
	(*StrategyStatus)(nil),             // 10: strategy.StrategyStatus
	(*StrategyRequest)(nil),            // 11: strategy.StrategyRequest
	nil,                                // 12: strategy.Signal.IndicatorsEntry
	nil,                                // 13: strategy.StrategyConfig.ParametersEntry
}
var file_strategy_proto_depIdxs = []int32{
	4,  // 0: strategy.SignalReason.allocator:type_name -> strategy.PositionAllocatorStatus
	1,  // 1: strategy.SignalReason.range:type_name -> strategy.RangeSignalReason
	12, // 2: strategy.Signal.indicators:type_name -> strategy.Signal.IndicatorsEntry
	0,  // 3: strategy.Signal.signal_reason:type_name -> strategy.SignalReason
	13, // 4: strategy.StrategyConfig.parameters:type_name -> strategy.StrategyConfig.ParametersEntry
	5,  // 5: strategy.RegimeFusionStatus.h1:type_name -> strategy.RegimeFrameStatus
	5,  // 6: strategy.RegimeFusionStatus.m15:type_name -> strategy.RegimeFrameStatus
	6,  // 7: strategy.StrategyRouteRuntimeStatus.regime_fusion:type_name -> strategy.RegimeFusionStatus
	7,  // 8: strategy.StrategyRouteRuntimeStatus.warmup:type_name -> strategy.StrategyWarmupStatus
	8,  // 9: strategy.StrategyRouteRuntimeStatus.latest_second_bar:type_name -> strategy.LatestSecondBarStatus
	4,  // 10: strategy.StrategyStatus.allocator:type_name -> strategy.PositionAllocatorStatus
	9,  // 11: strategy.StrategyStatus.router:type_name -> strategy.StrategyRouteRuntimeStatus
	3,  // 12: strategy.StrategyService.StartStrategy:input_type -> strategy.StrategyConfig
	11, // 13: strategy.StrategyService.StopStrategy:input_type -> strategy.StrategyRequest
	11, // 14: strategy.StrategyService.GetStrategyStatus:input_type -> strategy.StrategyRequest
	11, // 15: strategy.StrategyService.StreamSignals:input_type -> strategy.StrategyRequest
	10, // 16: strategy.StrategyService.StartStrategy:output_type -> strategy.StrategyStatus
	10, // 17: strategy.StrategyService.StopStrategy:output_type -> strategy.StrategyStatus
	10, // 18: strategy.StrategyService.GetStrategyStatus:output_type -> strategy.StrategyStatus
	2,  // 19: strategy.StrategyService.StreamSignals:output_type -> strategy.Signal
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_strategy_proto_init() }
func file_strategy_proto_init() {
	if File_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_proto_goTypes,
		DependencyIndexes: file_strategy_proto_depIdxs,
		MessageInfos:      file_strategy_proto_msgTypes,
	}.Build()
	File_strategy_proto = out.File
	file_strategy_proto_goTypes = nil
	file_strategy_proto_depIdxs = nil
}
