// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: strategy.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 交易信号 — execution 只消费此消息，不消费原始K线
//
// 数据流：Market(Kline) → Strategy(分析+决策) → Signal → Execution(下单+风控)
//
// Signal 包含"可执行"信息：方向、数量、止损止盈、信号类型
// 不包含：原始K线数据、中间指标计算过程
type SignalReason struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Summary          string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`                                           // 兼容旧链路的摘要描述
	Phase            string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`                                               // OPEN_ENTRY / CLOSE_EXIT
	TrendContext     string                 `protobuf:"bytes,3,opt,name=trend_context,json=trendContext,proto3" json:"trend_context,omitempty"`             // 大级别趋势背景
	SetupContext     string                 `protobuf:"bytes,4,opt,name=setup_context,json=setupContext,proto3" json:"setup_context,omitempty"`             // 入场/出场触发背景
	PathContext      string                 `protobuf:"bytes,5,opt,name=path_context,json=pathContext,proto3" json:"path_context,omitempty"`                // 收割路径或盘口路径背景
	ExecutionContext string                 `protobuf:"bytes,6,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"` // 止损止盈、仓位、确认条件等执行信息
	Tags             []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`                                                 // 标签，如 ["15m", "trend_following", "long"]
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignalReason) Reset() {
	*x = SignalReason{}
	mi := &file_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalReason) ProtoMessage() {}

func (x *SignalReason) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalReason.ProtoReflect.Descriptor instead.
func (*SignalReason) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *SignalReason) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SignalReason) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SignalReason) GetTrendContext() string {
	if x != nil {
		return x.TrendContext
	}
	return ""
}

func (x *SignalReason) GetSetupContext() string {
	if x != nil {
		return x.SetupContext
	}
	return ""
}

func (x *SignalReason) GetPathContext() string {
	if x != nil {
		return x.PathContext
	}
	return ""
}

func (x *SignalReason) GetExecutionContext() string {
	if x != nil {
		return x.ExecutionContext
	}
	return ""
}

func (x *SignalReason) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Signal struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	StrategyId  string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`             // 策略ID，如 "trend-following-BTCUSDT"
	Symbol      string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                       // 交易对，如 "BTCUSDT"
	Action      string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                       // 动作：BUY, SELL, HOLD
	Side        string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"`                                           // 仓位方向：LONG, SHORT
	Quantity    float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`                                 // 下单数量
	EntryPrice  float64                `protobuf:"fixed64,6,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`           // 入场/出场价格
	StopLoss    float64                `protobuf:"fixed64,7,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`                 // 止损价
	TakeProfits []float64              `protobuf:"fixed64,8,rep,packed,name=take_profits,json=takeProfits,proto3" json:"take_profits,omitempty"` // 止盈价列表
	Reason      string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`                                       // 兼容旧链路的摘要原因
	Timestamp   int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                               // 信号时间戳（毫秒）
	SignalType  string                 `protobuf:"bytes,11,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`            // 信号类型：OPEN=开仓, CLOSE=平仓, HOLD=持仓观察
	Interval    string                 `protobuf:"bytes,12,opt,name=interval,proto3" json:"interval,omitempty"`                                  // 信号周期，如 "15m"
	Atr         float64                `protobuf:"fixed64,13,opt,name=atr,proto3" json:"atr,omitempty"`                                          // 当前ATR（execution用于计算滑点容忍度）
	RiskReward  float64                `protobuf:"fixed64,14,opt,name=risk_reward,json=riskReward,proto3" json:"risk_reward,omitempty"`          // 风险收益比（如 2.0 表示盈亏比 1:2）
	// 指标快照 — 供日志/审计用，execution 不做计算
	Indicators    map[string]float64 `protobuf:"bytes,15,rep,name=indicators,proto3" json:"indicators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // 如 {"h4_ema21":68000, "m15_rsi":62.3, "m15_atr":350}
	SignalReason  *SignalReason      `protobuf:"bytes,16,opt,name=signal_reason,json=signalReason,proto3" json:"signal_reason,omitempty"`                                                     // 结构化原因描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *Signal) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *Signal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Signal) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Signal) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Signal) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Signal) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *Signal) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *Signal) GetTakeProfits() []float64 {
	if x != nil {
		return x.TakeProfits
	}
	return nil
}

func (x *Signal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Signal) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Signal) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *Signal) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *Signal) GetAtr() float64 {
	if x != nil {
		return x.Atr
	}
	return 0
}

func (x *Signal) GetRiskReward() float64 {
	if x != nil {
		return x.RiskReward
	}
	return 0
}

func (x *Signal) GetIndicators() map[string]float64 {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *Signal) GetSignalReason() *SignalReason {
	if x != nil {
		return x.SignalReason
	}
	return nil
}

// 策略配置
type StrategyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Parameters    map[string]float64     `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyConfig) Reset() {
	*x = StrategyConfig{}
	mi := &file_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyConfig) ProtoMessage() {}

func (x *StrategyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyConfig.ProtoReflect.Descriptor instead.
func (*StrategyConfig) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *StrategyConfig) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StrategyConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StrategyConfig) GetParameters() map[string]float64 {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *StrategyConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 策略状态
type StrategyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // RUNNING, STOPPED, ERROR
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LastUpdate    int64                  `protobuf:"varint,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyStatus) Reset() {
	*x = StrategyStatus{}
	mi := &file_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyStatus) ProtoMessage() {}

func (x *StrategyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyStatus.ProtoReflect.Descriptor instead.
func (*StrategyStatus) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *StrategyStatus) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *StrategyStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StrategyStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StrategyStatus) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

type StrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyRequest) Reset() {
	*x = StrategyRequest{}
	mi := &file_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyRequest) ProtoMessage() {}

func (x *StrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyRequest.ProtoReflect.Descriptor instead.
func (*StrategyRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *StrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

var File_strategy_proto protoreflect.FileDescriptor

const file_strategy_proto_rawDesc = "" +
	"\n" +
	"\x0estrategy.proto\x12\bstrategy\"\xec\x01\n" +
	"\fSignalReason\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12#\n" +
	"\rtrend_context\x18\x03 \x01(\tR\ftrendContext\x12#\n" +
	"\rsetup_context\x18\x04 \x01(\tR\fsetupContext\x12!\n" +
	"\fpath_context\x18\x05 \x01(\tR\vpathContext\x12+\n" +
	"\x11execution_context\x18\x06 \x01(\tR\x10executionContext\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\xce\x04\n" +
	"\x06Signal\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x1f\n" +
	"\ventry_price\x18\x06 \x01(\x01R\n" +
	"entryPrice\x12\x1b\n" +
	"\tstop_loss\x18\a \x01(\x01R\bstopLoss\x12!\n" +
	"\ftake_profits\x18\b \x03(\x01R\vtakeProfits\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vsignal_type\x18\v \x01(\tR\n" +
	"signalType\x12\x1a\n" +
	"\binterval\x18\f \x01(\tR\binterval\x12\x10\n" +
	"\x03atr\x18\r \x01(\x01R\x03atr\x12\x1f\n" +
	"\vrisk_reward\x18\x0e \x01(\x01R\n" +
	"riskReward\x12@\n" +
	"\n" +
	"indicators\x18\x0f \x03(\v2 .strategy.Signal.IndicatorsEntryR\n" +
	"indicators\x12;\n" +
	"\rsignal_reason\x18\x10 \x01(\v2\x16.strategy.SignalReasonR\fsignalReason\x1a=\n" +
	"\x0fIndicatorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xdf\x01\n" +
	"\x0eStrategyConfig\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12H\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2(.strategy.StrategyConfig.ParametersEntryR\n" +
	"parameters\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x84\x01\n" +
	"\x0eStrategyStatus\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vlast_update\x18\x04 \x01(\x03R\n" +
	"lastUpdate\"2\n" +
	"\x0fStrategyRequest\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\tR\n" +
	"strategyId2\xad\x02\n" +
	"\x0fStrategyService\x12E\n" +
	"\rStartStrategy\x12\x18.strategy.StrategyConfig\x1a\x18.strategy.StrategyStatus\"\x00\x12E\n" +
	"\fStopStrategy\x12\x19.strategy.StrategyRequest\x1a\x18.strategy.StrategyStatus\"\x00\x12J\n" +
	"\x11GetStrategyStatus\x12\x19.strategy.StrategyRequest\x1a\x18.strategy.StrategyStatus\"\x00\x12@\n" +
	"\rStreamSignals\x12\x19.strategy.StrategyRequest\x1a\x10.strategy.Signal\"\x000\x01B$Z\"exchange-system/common/pb/strategyb\x06proto3"

var (
	file_strategy_proto_rawDescOnce sync.Once
	file_strategy_proto_rawDescData []byte
)

func file_strategy_proto_rawDescGZIP() []byte {
	file_strategy_proto_rawDescOnce.Do(func() {
		file_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)))
	})
	return file_strategy_proto_rawDescData
}

var file_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_strategy_proto_goTypes = []any{
	(*SignalReason)(nil),    // 0: strategy.SignalReason
	(*Signal)(nil),          // 1: strategy.Signal
	(*StrategyConfig)(nil),  // 2: strategy.StrategyConfig
	(*StrategyStatus)(nil),  // 3: strategy.StrategyStatus
	(*StrategyRequest)(nil), // 4: strategy.StrategyRequest
	nil,                     // 5: strategy.Signal.IndicatorsEntry
	nil,                     // 6: strategy.StrategyConfig.ParametersEntry
}
var file_strategy_proto_depIdxs = []int32{
	5, // 0: strategy.Signal.indicators:type_name -> strategy.Signal.IndicatorsEntry
	0, // 1: strategy.Signal.signal_reason:type_name -> strategy.SignalReason
	6, // 2: strategy.StrategyConfig.parameters:type_name -> strategy.StrategyConfig.ParametersEntry
	2, // 3: strategy.StrategyService.StartStrategy:input_type -> strategy.StrategyConfig
	4, // 4: strategy.StrategyService.StopStrategy:input_type -> strategy.StrategyRequest
	4, // 5: strategy.StrategyService.GetStrategyStatus:input_type -> strategy.StrategyRequest
	4, // 6: strategy.StrategyService.StreamSignals:input_type -> strategy.StrategyRequest
	3, // 7: strategy.StrategyService.StartStrategy:output_type -> strategy.StrategyStatus
	3, // 8: strategy.StrategyService.StopStrategy:output_type -> strategy.StrategyStatus
	3, // 9: strategy.StrategyService.GetStrategyStatus:output_type -> strategy.StrategyStatus
	1, // 10: strategy.StrategyService.StreamSignals:output_type -> strategy.Signal
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_strategy_proto_init() }
func file_strategy_proto_init() {
	if File_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_proto_goTypes,
		DependencyIndexes: file_strategy_proto_depIdxs,
		MessageInfos:      file_strategy_proto_msgTypes,
	}.Build()
	File_strategy_proto = out.File
	file_strategy_proto_goTypes = nil
	file_strategy_proto_depIdxs = nil
}
