// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: matching.proto

package server

import (
	"context"

	"exchange-system/rpc/matching/exchange/rpc/matching/matching"
	"exchange-system/rpc/matching/internal/logic"
	"exchange-system/rpc/matching/internal/svc"
)

type MatchingServer struct {
	svcCtx *svc.ServiceContext
	matching.UnimplementedMatchingServer
}

func NewMatchingServer(svcCtx *svc.ServiceContext) *MatchingServer {
	return &MatchingServer{
		svcCtx: svcCtx,
	}
}

func (s *MatchingServer) SubmitOrder(ctx context.Context, in *matching.OrderRequest) (*matching.OrderResponse, error) {
	l := logic.NewSubmitOrderLogic(ctx, s.svcCtx)
	return l.SubmitOrder(in)
}

func (s *MatchingServer) CancelOrder(ctx context.Context, in *matching.CancelOrderRequest) (*matching.CancelOrderResponse, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

func (s *MatchingServer) GetOrderBook(ctx context.Context, in *matching.GetOrderBookRequest) (*matching.GetOrderBookResponse, error) {
	l := logic.NewGetOrderBookLogic(ctx, s.svcCtx)
	return l.GetOrderBook(in)
}
