// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: strategy.proto

package server

import (
	"context"

	"exchange-system/app/strategy/rpc/internal/logic"
	"exchange-system/app/strategy/rpc/internal/svc"
	"exchange-system/common/pb/strategy"
)

type StrategyServiceServer struct {
	svcCtx *svc.ServiceContext
	strategy.UnimplementedStrategyServiceServer
}

func NewStrategyServiceServer(svcCtx *svc.ServiceContext) *StrategyServiceServer {
	return &StrategyServiceServer{
		svcCtx: svcCtx,
	}
}

// 启动策略
func (s *StrategyServiceServer) StartStrategy(ctx context.Context, in *strategy.StrategyConfig) (*strategy.StrategyStatus, error) {
	l := logic.NewStartStrategyLogic(ctx, s.svcCtx)
	return l.StartStrategy(in)
}

// 停止策略
func (s *StrategyServiceServer) StopStrategy(ctx context.Context, in *strategy.StrategyRequest) (*strategy.StrategyStatus, error) {
	l := logic.NewStopStrategyLogic(ctx, s.svcCtx)
	return l.StopStrategy(in)
}

// 获取策略状态
func (s *StrategyServiceServer) GetStrategyStatus(ctx context.Context, in *strategy.StrategyRequest) (*strategy.StrategyStatus, error) {
	l := logic.NewGetStrategyStatusLogic(ctx, s.svcCtx)
	return l.GetStrategyStatus(in)
}

// 获取策略信号流
func (s *StrategyServiceServer) StreamSignals(in *strategy.StrategyRequest, stream strategy.StrategyService_StreamSignalsServer) error {
	l := logic.NewStreamSignalsLogic(stream.Context(), s.svcCtx)
	return l.StreamSignals(in, stream)
}
