// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package server

import (
	"context"

	"exchange-system/app/order/rpc/internal/logic"
	"exchange-system/app/order/rpc/internal/svc"
	"exchange-system/common/pb/order"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// 查询当前委托（未成交订单）
func (s *OrderServiceServer) GetOpenOrders(ctx context.Context, in *order.OrderQueryRequest) (*order.OpenOrderResponse, error) {
	l := logic.NewGetOpenOrdersLogic(ctx, s.svcCtx)
	return l.GetOpenOrders(in)
}

// 查询历史委托
func (s *OrderServiceServer) GetAllOrders(ctx context.Context, in *order.OrderQueryRequest) (*order.AllOrderResponse, error) {
	l := logic.NewGetAllOrdersLogic(ctx, s.svcCtx)
	return l.GetAllOrders(in)
}

// 查询历史成交
func (s *OrderServiceServer) GetUserTrades(ctx context.Context, in *order.OrderQueryRequest) (*order.UserTradeResponse, error) {
	l := logic.NewGetUserTradesLogic(ctx, s.svcCtx)
	return l.GetUserTrades(in)
}

// 查询资金流水
func (s *OrderServiceServer) GetIncomeHistory(ctx context.Context, in *order.OrderQueryRequest) (*order.IncomeResponse, error) {
	l := logic.NewGetIncomeHistoryLogic(ctx, s.svcCtx)
	return l.GetIncomeHistory(in)
}

// 查询资金费率历史
func (s *OrderServiceServer) GetFundingRateHistory(ctx context.Context, in *order.OrderQueryRequest) (*order.FundingRateResponse, error) {
	l := logic.NewGetFundingRateHistoryLogic(ctx, s.svcCtx)
	return l.GetFundingRateHistory(in)
}

// 查询资金费用
func (s *OrderServiceServer) GetFundingFees(ctx context.Context, in *order.OrderQueryRequest) (*order.FundingFeeResponse, error) {
	l := logic.NewGetFundingFeesLogic(ctx, s.svcCtx)
	return l.GetFundingFees(in)
}

// 拉取全部数据并保存到本地 JSONL
func (s *OrderServiceServer) FetchAllData(ctx context.Context, in *order.OrderQueryRequest) (*order.EmptyRequest, error) {
	l := logic.NewFetchAllDataLogic(ctx, s.svcCtx)
	return l.FetchAllData(in)
}
